// GENERATED by crates/don-replay/gen/gen_wire.py from schema/command-wire.json.
// Do not edit by hand; edit the generator or the schema.
//
// Source: 82 CommandTypes opcodes with the exact field layout the PDB type
// stream gives for each *Command struct, cross-checked against the byte length
// each handler returns (schema/command-wire.json).

use crate::wire::{Field, FieldKind};

pub const NUM_OPCODES: usize = 82;

pub(crate) static F_00: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "num", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::I8, width: 1, name: "who", ty: "char" },
    Field { off: 3, kind: FieldKind::Opaque, width: 0, name: "list", ty: "GroupCommand::<unnamed-type-list>[2]" },
];
pub(crate) static F_01: &[Field] = &[
];
pub(crate) static F_02: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "stance", ty: "int" },
];
pub(crate) static F_03: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "form", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "rotate", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_04: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "ignore", ty: "int" },
    Field { off: 13, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_05: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_06: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "orders", ty: "int" },
];
pub(crate) static F_07: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "to_x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "to_y", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "set_angle", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "angle", ty: "int" },
    Field { off: 17, kind: FieldKind::I8, width: 1, name: "orders", ty: "char" },
    Field { off: 18, kind: FieldKind::I8, width: 1, name: "queued", ty: "char" },
    Field { off: 19, kind: FieldKind::I8, width: 1, name: "form", ty: "char" },
    Field { off: 20, kind: FieldKind::I8, width: 1, name: "width", ty: "char" },
    Field { off: 21, kind: FieldKind::I8, width: 1, name: "disembark", ty: "char" },
];
pub(crate) static F_08: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "to_x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "to_y", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "tolerance", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "set_angle", ty: "int" },
    Field { off: 17, kind: FieldKind::I32, width: 4, name: "angle", ty: "int" },
    Field { off: 21, kind: FieldKind::I8, width: 1, name: "orders", ty: "char" },
    Field { off: 22, kind: FieldKind::I8, width: 1, name: "queued", ty: "char" },
    Field { off: 23, kind: FieldKind::I8, width: 1, name: "form", ty: "char" },
    Field { off: 24, kind: FieldKind::I8, width: 1, name: "width", ty: "char" },
    Field { off: 25, kind: FieldKind::I8, width: 1, name: "disembark", ty: "char" },
];
pub(crate) static F_09: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "to_x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "to_y", ty: "int" },
    Field { off: 9, kind: FieldKind::I8, width: 1, name: "queued", ty: "char" },
];
pub(crate) static F_0A: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "to_x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "to_y", ty: "int" },
    Field { off: 9, kind: FieldKind::I8, width: 1, name: "queued", ty: "char" },
];
pub(crate) static F_0B: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "to_x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "to_y", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "shift", ty: "int" },
    Field { off: 17, kind: FieldKind::I32, width: 4, name: "ctrl", ty: "int" },
    Field { off: 21, kind: FieldKind::I32, width: 4, name: "alt", ty: "int" },
];
pub(crate) static F_0C: &[Field] = &[
];
pub(crate) static F_0D: &[Field] = &[
];
pub(crate) static F_0E: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "flag", ty: "int" },
];
pub(crate) static F_0F: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_10: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_11: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "oxx", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "whose", ty: "int" },
    Field { off: 17, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_12: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "t", ty: "int" },
    Field { off: 5, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_13: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_14: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_15: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "all", ty: "int" },
];
pub(crate) static F_16: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "y", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "action", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "add_to_end", ty: "int" },
];
pub(crate) static F_17: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "type", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "x", ty: "int" },
    Field { off: 17, kind: FieldKind::I32, width: 4, name: "y", ty: "int" },
];
pub(crate) static F_18: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "type", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "num", ty: "int" },
];
pub(crate) static F_19: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "x", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "y", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "x2", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "y2", ty: "int" },
    Field { off: 17, kind: FieldKind::I32, width: 4, name: "type", ty: "int" },
    Field { off: 21, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_1A: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "back_to_work", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "eject_o", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "eject_who", ty: "int" },
];
pub(crate) static F_1B: &[Field] = &[
];
pub(crate) static F_1C: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "shift", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "ctrl", ty: "int" },
    Field { off: 17, kind: FieldKind::I32, width: 4, name: "alt", ty: "int" },
    Field { off: 21, kind: FieldKind::I32, width: 4, name: "orders", ty: "OrderIndex" },
];
pub(crate) static F_1D: &[Field] = &[
];
pub(crate) static F_1E: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_1F: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "ox", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "queued", ty: "QueuePos" },
];
pub(crate) static F_20: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "unitmask", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "set", ty: "int" },
];
pub(crate) static F_21: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "buildmask", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "set", ty: "int" },
];
pub(crate) static F_22: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "group", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "clear", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "valid", ty: "int" },
    Field { off: 13, kind: FieldKind::F32, width: 4, name: "x", ty: "float" },
    Field { off: 17, kind: FieldKind::F32, width: 4, name: "y", ty: "float" },
    Field { off: 21, kind: FieldKind::I32, width: 4, name: "zoom", ty: "int" },
];
pub(crate) static F_23: &[Field] = &[
];
pub(crate) static F_24: &[Field] = &[
];
pub(crate) static F_25: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "treaty", ty: "int" },
];
pub(crate) static F_26: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "treaty", ty: "int" },
];
pub(crate) static F_27: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
];
pub(crate) static F_28: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
];
pub(crate) static F_29: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
];
pub(crate) static F_2A: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
];
pub(crate) static F_2B: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "good", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "amount", ty: "int" },
];
pub(crate) static F_2C: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "good", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "amount", ty: "int" },
];
pub(crate) static F_2D: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "whom", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "whose", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "onoff", ty: "int" },
];
pub(crate) static F_2E: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "good", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "flags", ty: "int" },
];
pub(crate) static F_2F: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "good", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "flags", ty: "int" },
];
pub(crate) static F_30: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "o", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "type", ty: "int" },
    Field { off: 13, kind: FieldKind::I16, width: 2, name: "uid", ty: "short" },
];
pub(crate) static F_31: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "o", ty: "int" },
    Field { off: 9, kind: FieldKind::I16, width: 2, name: "uid", ty: "short" },
];
pub(crate) static F_32: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "x", ty: "Coord" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "y", ty: "Coord" },
];
pub(crate) static F_33: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "spline_type", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::U8, width: 1, name: "spline_flags", ty: "unsigned char" },
    Field { off: 3, kind: FieldKind::U8, width: 1, name: "spline_cmd", ty: "unsigned char" },
    Field { off: 4, kind: FieldKind::U16, width: 2, name: "len", ty: "unsigned short" },
    Field { off: 6, kind: FieldKind::Opaque, width: 0, name: "vert_data", ty: "SplineCommand::<unnamed-type-vert_data>[8]" },
];
pub(crate) static F_34: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "speed", ty: "int" },
];
pub(crate) static F_35: &[Field] = &[
];
pub(crate) static F_36: &[Field] = &[
];
pub(crate) static F_37: &[Field] = &[
];
pub(crate) static F_38: &[Field] = &[
    Field { off: 1, kind: FieldKind::U32, width: 4, name: "seed", ty: "unsigned long" },
];
pub(crate) static F_39: &[Field] = &[
    Field { off: 1, kind: FieldKind::U32, width: 4, name: "units_checksum", ty: "unsigned long" },
    Field { off: 5, kind: FieldKind::U32, width: 4, name: "builds_checksum", ty: "unsigned long" },
    Field { off: 9, kind: FieldKind::U32, width: 4, name: "walls_checksum", ty: "unsigned long" },
    Field { off: 13, kind: FieldKind::U32, width: 4, name: "ammo_checksum", ty: "unsigned long" },
    Field { off: 17, kind: FieldKind::U32, width: 4, name: "deaths_checksum", ty: "unsigned long" },
    Field { off: 21, kind: FieldKind::U32, width: 4, name: "groups_checksum", ty: "unsigned long" },
    Field { off: 25, kind: FieldKind::U32, width: 4, name: "guys_checksum", ty: "unsigned long" },
    Field { off: 29, kind: FieldKind::U32, width: 4, name: "leaders_checksum", ty: "unsigned long" },
    Field { off: 33, kind: FieldKind::U32, width: 4, name: "cities_checksum", ty: "unsigned long" },
    Field { off: 37, kind: FieldKind::U32, width: 4, name: "items_checksum", ty: "unsigned long" },
    Field { off: 41, kind: FieldKind::U32, width: 4, name: "goods_checksum", ty: "unsigned long" },
    Field { off: 45, kind: FieldKind::U32, width: 4, name: "world_checksum", ty: "unsigned long" },
    Field { off: 49, kind: FieldKind::U32, width: 4, name: "rules_checksum", ty: "unsigned long" },
    Field { off: 53, kind: FieldKind::U32, width: 4, name: "scenario_data_checksum", ty: "unsigned long" },
    Field { off: 57, kind: FieldKind::U32, width: 4, name: "script_run_time_checksum", ty: "unsigned long" },
    Field { off: 61, kind: FieldKind::U32, width: 4, name: "all_checksum", ty: "unsigned long" },
];
pub(crate) static F_3A: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "checksum_type", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::U32, width: 4, name: "checksum", ty: "unsigned long" },
];
pub(crate) static F_3B: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
];
pub(crate) static F_3C: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
];
pub(crate) static F_3D: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
];
pub(crate) static F_3E: &[Field] = &[
];
pub(crate) static F_3F: &[Field] = &[
];
pub(crate) static F_40: &[Field] = &[
];
pub(crate) static F_41: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
];
pub(crate) static F_42: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
];
pub(crate) static F_43: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "t", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "x", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "y", ty: "int" },
];
pub(crate) static F_44: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "bits", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "taunt", ty: "int" },
    Field { off: 9, kind: FieldKind::I32, width: 4, name: "taunt_num", ty: "int" },
    Field { off: 13, kind: FieldKind::I32, width: 4, name: "len", ty: "int" },
    Field { off: 17, kind: FieldKind::Opaque, width: 0, name: "string", ty: "wchar_t[1]" },
];
pub(crate) static F_45: &[Field] = &[
    Field { off: 1, kind: FieldKind::Opaque, width: 0, name: "status", ty: "unsigned char[8]" },
];
pub(crate) static F_46: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "play", ty: "int" },
];
pub(crate) static F_47: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "play", ty: "int" },
    Field { off: 5, kind: FieldKind::U8, width: 1, name: "replay", ty: "unsigned char" },
    Field { off: 6, kind: FieldKind::U8, width: 1, name: "system_quit", ty: "unsigned char" },
];
pub(crate) static F_48: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "zoom", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::I32, width: 4, name: "x_loc", ty: "int" },
    Field { off: 6, kind: FieldKind::I32, width: 4, name: "y_loc", ty: "int" },
];
pub(crate) static F_49: &[Field] = &[
    Field { off: 1, kind: FieldKind::Opaque, width: 0, name: "leader_option", ty: "LeaderOptionData" },
];
pub(crate) static F_4A: &[Field] = &[
    Field { off: 1, kind: FieldKind::U16, width: 2, name: "ping_time", ty: "unsigned short" },
    Field { off: 3, kind: FieldKind::U16, width: 2, name: "frame_average", ty: "unsigned short" },
    Field { off: 5, kind: FieldKind::U16, width: 2, name: "wait_time", ty: "unsigned short" },
    Field { off: 7, kind: FieldKind::U16, width: 2, name: "game_lag", ty: "unsigned short" },
    Field { off: 9, kind: FieldKind::U16, width: 2, name: "forced_loads", ty: "unsigned short" },
];
pub(crate) static F_4B: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "who", ty: "int" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "o", ty: "int" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "name", ty: "wchar_t[22]" },
];
pub(crate) static F_4C: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "state", ty: "unsigned char" },
];
pub(crate) static F_4D: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "state", ty: "unsigned char" },
];
pub(crate) static F_4E: &[Field] = &[
    Field { off: 1, kind: FieldKind::I32, width: 4, name: "mouse_x", ty: "Coord" },
    Field { off: 5, kind: FieldKind::I32, width: 4, name: "mouse_y", ty: "Coord" },
    Field { off: 9, kind: FieldKind::Opaque, width: 0, name: "cmd", ty: "wchar_t[256]" },
];
pub(crate) static F_4F: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "accum_frames_zoomed_in", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::U8, width: 1, name: "accum_frames_zoomed_out", ty: "unsigned char" },
    Field { off: 3, kind: FieldKind::U8, width: 1, name: "accum_clicks", ty: "unsigned char" },
    Field { off: 4, kind: FieldKind::U8, width: 1, name: "accum_hotkeys", ty: "unsigned char" },
    Field { off: 5, kind: FieldKind::U8, width: 1, name: "accum_minimap_clicks", ty: "unsigned char" },
    Field { off: 6, kind: FieldKind::U8, width: 1, name: "accum_mainmap_clicks", ty: "unsigned char" },
    Field { off: 7, kind: FieldKind::U8, width: 1, name: "accum_control_groups_formed", ty: "unsigned char" },
    Field { off: 8, kind: FieldKind::U8, width: 1, name: "accum_control_groups_activated", ty: "unsigned char" },
];
pub(crate) static F_50: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "play", ty: "unsigned char" },
    Field { off: 2, kind: FieldKind::U8, width: 1, name: "state", ty: "unsigned char" },
];
pub(crate) static F_51: &[Field] = &[
    Field { off: 1, kind: FieldKind::U8, width: 1, name: "start", ty: "unsigned char" },
];

pub static COMMAND_FIELDS: [&[Field]; NUM_OPCODES] = [
    F_00,
    F_01,
    F_02,
    F_03,
    F_04,
    F_05,
    F_06,
    F_07,
    F_08,
    F_09,
    F_0A,
    F_0B,
    F_0C,
    F_0D,
    F_0E,
    F_0F,
    F_10,
    F_11,
    F_12,
    F_13,
    F_14,
    F_15,
    F_16,
    F_17,
    F_18,
    F_19,
    F_1A,
    F_1B,
    F_1C,
    F_1D,
    F_1E,
    F_1F,
    F_20,
    F_21,
    F_22,
    F_23,
    F_24,
    F_25,
    F_26,
    F_27,
    F_28,
    F_29,
    F_2A,
    F_2B,
    F_2C,
    F_2D,
    F_2E,
    F_2F,
    F_30,
    F_31,
    F_32,
    F_33,
    F_34,
    F_35,
    F_36,
    F_37,
    F_38,
    F_39,
    F_3A,
    F_3B,
    F_3C,
    F_3D,
    F_3E,
    F_3F,
    F_40,
    F_41,
    F_42,
    F_43,
    F_44,
    F_45,
    F_46,
    F_47,
    F_48,
    F_49,
    F_4A,
    F_4B,
    F_4C,
    F_4D,
    F_4E,
    F_4F,
    F_50,
    F_51,
];

/// `*Command` struct name per opcode, from the PDB.
pub static COMMAND_STRUCT: [&str; NUM_OPCODES] = [
    "GroupCommand",
    "BeginCommand",
    "StanceCommand",
    "FormCommand",
    "AttackCommand",
    "SiegeAttackCommand",
    "SwarmAroundCommand",
    "MoveToCommand",
    "MoveNearCommand",
    "AttackGroundCommand",
    "PatrolCommand",
    "LaunchPatrolCommand",
    "HaltCommand",
    "TransportCommand",
    "SetTransportCommand",
    "BoardShipCommand",
    "RepairCommand",
    "TradeCommand",
    "CityGatherCommand",
    "GatherCommand",
    "GarrisonCommand",
    "DisbandCommand",
    "GatherPointCommand",
    "SpellCommand",
    "QueueUpCommand",
    "BuildCommand",
    "EjectAllCommand",
    "AlarmCommand",
    "FlightCommand",
    "StopSpellCommand",
    "FollowCommand",
    "GuardCommand",
    "UnitmaskCommand",
    "BuildmaskCommand",
    "HotKeyCommand",
    "RecallCommand",
    "ScrambleCommand",
    "TreatyCommand",
    "DeclareCommand",
    "ClearTributesCommand",
    "ClearAllCommand",
    "AcceptCommand",
    "RejectCommand",
    "TributeCommand",
    "DemandTributeCommand",
    "ProposeAttackCommand",
    "BuyCommand",
    "SellCommand",
    "UnqueueCommand",
    "ComeOutCommand",
    "PingCommand",
    "SplineCommand",
    "SpeedSetCommand",
    "SpeedUpCommand",
    "SpeedDownCommand",
    "MPLogCommand",
    "CheckRandomCommand",
    "CheckSumsCommand",
    "NextCheckSumCommand",
    "CheatViewAllCommand",
    "CheatGiveTechsCommand",
    "CheatZeroTechsCommand",
    "CheatAISpeedIncreaseCommand",
    "CheatAISpeedNormalCommand",
    "CheatAIToggleCommand",
    "CheatIncreaseBucketsCommand",
    "CheatZeroBucketsCommand",
    "CheatInitUnitCommand",
    "ChatCommand",
    "ChatSetCommand",
    "ResignCommand",
    "QuitCommand",
    "CameraCommand",
    "LeaderOptionsCommand",
    "TurnDataCommand",
    "RenameCityCommand",
    "PauseCommand",
    "CannonTimeCommand",
    "ConsoleCmdCommand",
    "PlayerSpeedCommand",
    "UngracefulPlayerDrop",
    "MarwanCommand",
];

/// `CommandPackage::process_*` handler name per opcode, from the PDB.
pub static COMMAND_METHOD: [&str; NUM_OPCODES] = [
    "process_group",
    "process_begin",
    "process_stance",
    "process_form",
    "process_attack",
    "process_siege_attack",
    "process_swarm_around",
    "process_move_to",
    "process_move_near",
    "process_attack_ground",
    "process_patrol",
    "process_launch_patrol",
    "process_halt",
    "process_transport",
    "process_set_transport",
    "process_board_ship",
    "process_repair",
    "process_trade",
    "process_city_gather",
    "process_gather",
    "process_garrison",
    "process_disband",
    "process_gather_point",
    "process_spell",
    "process_queue_up",
    "process_build",
    "process_eject_all",
    "process_alarm",
    "process_flight",
    "process_stop_spell",
    "process_follow",
    "process_guard",
    "process_unitmask",
    "process_buildmask",
    "process_hotkey",
    "process_recall",
    "process_scramble",
    "process_treaty",
    "process_declare",
    "process_clear_tributes",
    "process_clear_all",
    "process_accept",
    "process_reject",
    "process_tribute",
    "process_demand_tribute",
    "process_propose_attack",
    "process_buy",
    "process_sell",
    "process_unqueue",
    "process_come_out",
    "process_ping",
    "process_spline",
    "process_speed_set",
    "process_speed_up",
    "process_speed_down",
    "process_mp_log",
    "process_check_random",
    "process_check_sums",
    "process_next_check_sum",
    "process_cheat_view_all",
    "process_cheat_give_techs",
    "process_cheat_zero_techs",
    "process_cheat_ai_speed_increase",
    "process_cheat_ai_speed_normal",
    "process_cheat_ai_toggle",
    "process_cheat_increase_buckets",
    "process_cheat_zero_buckets",
    "process_cheat_init_unit",
    "process_chat",
    "process_chat_set",
    "process_resign",
    "process_quit",
    "process_camera",
    "process_leader_options",
    "process_turn_data",
    "process_rename_city",
    "process_pause",
    "process_cannon_time",
    "process_console_cmd",
    "process_player_speed",
    "process_ungraceful_player_drop",
    "process_marwan",
];

/// `sizeof(*Command)` per opcode. NOT the wire length for the three
/// variable-length opcodes (0x00, 0x33, 0x44) -- use `don_net::Command::wire_len`.
pub static COMMAND_SIZEOF: [u16; NUM_OPCODES] = [
    5,
    1,
    5,
    13,
    17,
    13,
    17,
    22,
    26,
    10,
    10,
    25,
    1,
    1,
    5,
    9,
    13,
    21,
    9,
    9,
    13,
    5,
    17,
    21,
    9,
    25,
    17,
    1,
    25,
    1,
    13,
    13,
    9,
    9,
    25,
    1,
    1,
    13,
    13,
    9,
    9,
    9,
    9,
    17,
    17,
    17,
    13,
    13,
    15,
    11,
    9,
    14,
    5,
    1,
    1,
    1,
    5,
    65,
    6,
    5,
    5,
    5,
    1,
    1,
    1,
    5,
    5,
    17,
    19,
    9,
    5,
    7,
    10,
    33,
    11,
    53,
    2,
    2,
    521,
    9,
    3,
    2,
];
