// SPDX-License-Identifier: GPL-3.0-or-later
//! `ScenarioFuncSet` — the 842 builtins that touch the game, and the first 21 of them.
//!
//! [`crate::builtins`] covers the four *utility* function sets, which need no simulation.
//! This module is the other side of that seam: builtins registered by `ScenarioFuncSet`
//! (`OP_CALL_GAME` indices 31..872), where the handler reads `Game`, `Leaders`, the object
//! bands or the script engine's own `ScenarioData`.
//!
//! # Why these twenty-one
//!
//! `ron-data/bhs-corpus/scenario/scriptlibrary/general_powers.bhs` — the second script
//! retail runs at tick step 4, made loadable by the script-load-path lane — calls exactly
//! **seven** builtins: `time_sec`, `set_timer`, `timer_expired`, `object_type_selected`,
//! `find_unit`, `length` and `bubble_text_obj`. `length` was already implemented. The
//! other six are here, so that script is now executable rather than merely loadable.
//!
//! Around them sit three cheap neighbours and the twelve zero-argument rules gates the
//! shipped AI opening book branches on:
//!
//! | index | name | handler | what it reads |
//! |---|---|---|---|
//! | 77 | `set_timer` | `0x009e4bc0` | `ScenarioData::timers`, `Game::tick` |
//! | 78 | `stop_timer` | `0x009e4c10` | `ScenarioData::timers` |
//! | 79 | `timer_expired` | `0x009e4c80` | `ScenarioData::timers`, `Game::tick` |
//! | 94 | `get_is_no_nation_powers` | `0x009e5230` | `GameInfo::flags` bit 2 |
//! | 95 | `get_rush_rules` | `0x009e5240` | `GameInfo::rush_rules` |
//! | 96..105 | `is_victory_*` | `0x009e5250`..`0x009e52e0` | `GameInfo::victory` |
//! | 147 | `is_conquest_scenario` | `0x009e6040` | `Game::semaphore` bit 17 |
//! | 298 | `time_sec` | `0x009ead40` | `Game::tick` |
//! | 311 | `find_unit` | `0x009ebe10` | `Units::lists`, `Leaders`, a static cursor |
//! | 390 | `object_type_selected` | `0x009f04e0` | the local selection group |
//! | 392 | `num_objects_selected` | `0x009f06f0` | the local selection group |
//! | 783 | `bubble_text_obj` | `0x009ff550` | the object band, `MessageWin` |
//!
//! # Where the boundary is, and why it is where it is
//!
//! Every handler above was read at the instruction level (see
//! `docs/mechanics/bhs-scenario-builtins.md` for the per-address derivation). The *guard
//! logic* — the 1-based `who`, the `who - 1 > 7` unsigned bound, the `Leaders` flag pair,
//! the empty-string cases, the `-1` / `0` / `1` return trichotomy, the static search cursor
//! — is the majority of each body and lives here, executed. What a handler reads out of
//! the simulation is a [`Host`] method that *names the retail address and field it stands
//! for*. A host that cannot answer yields [`HostError::Unimplemented`] and the VM stops;
//! nothing in this module substitutes a plausible number.
//!
//! `ScenarioData::timers` is different in kind: it is script-engine state, not simulation
//! state, so [`ScriptTimers`] is a complete reimplementation of the retail container and
//! runs entirely here.
//!
//! # Fidelity
//!
//! Tier C throughout. Static analysis of `ron-bin/riseofnations.exe` (PE32 i386, image
//! base `0x00400000`) with Capstone plus the matching private PDB. Nothing here has been
//! executed against retail. Not verified, not proven, not a refinement.

use std::collections::BTreeMap;

use crate::builtin_table::BuiltinDecl;
use crate::host::{Host, HostError, HostResult};
use crate::value::Value;

// ---------------------------------------------------------------------------
// String equality, as `String::operator==` performs it
// ---------------------------------------------------------------------------

/// `String::operator==` `0x00a1f140`, restricted to the subdomain it can be reproduced on.
///
/// The retail body, read at `0x00a1f140`:
///
/// 1. `curr_len` (`String+8`, a `short` count of UTF-16 code units) must match, else false;
/// 2. if **both** operands have `flags & 2` — hashes generated by
///    `String::generate_hashes` `0x00a1ee60` — it returns `hash2 == hash2`
///    (`String+0x10`) and nothing else. A hash collision reads as equal;
/// 3. otherwise it forwards to the CRT `_wcsicmp` (import `0x00ac5640`), i.e. a
///    **case-insensitive** compare.
///
/// Step 2 is a deliberate hole here. Reproducing it needs `String::generate_hash`
/// `0x00a1b6b0` and its 50-word table at `0x00b14500`, *and* a model of which `String`s
/// carry hashes — and `Value::Str` is an `Rc<String>` with no flags word, so don-bhs
/// cannot represent that state at all. Documented, not approximated.
///
/// Step 3 is reproduced for ASCII only. MSVCRT `towlower` in the startup locale folds
/// `A..Z` and nothing else; asserting that for U+0080.. would be a guess, so a pair that
/// is not byte-identical and is not wholly ASCII **poisons**.
pub fn string_eq(a: &str, b: &str) -> Result<bool, HostError> {
    // `curr_len` is a UTF-16 code-unit count, so this is the retail length test.
    if a.encode_utf16().count() != b.encode_utf16().count() {
        return Ok(false);
    }
    if a == b {
        return Ok(true);
    }
    if !a.is_ascii() || !b.is_ascii() {
        // Two different non-ASCII strings of equal length: folding is undetermined.
        return Err(HostError::Unimplemented);
    }
    Ok(a.eq_ignore_ascii_case(b))
}

// ---------------------------------------------------------------------------
// ScenarioData::timers
// ---------------------------------------------------------------------------

/// One live timer: a name and the `Game::tick` value at which it comes due.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Timer {
    /// `LLNode<String,int>+0x08`.
    pub name: String,
    /// `LLNode<String,int>+0x1c` — an absolute `Game::tick`, not a duration.
    pub expires_at: i32,
}

/// `ScenarioData::timers` `0x00ed6650` — a `LinkListBase<String,int,LLNode<String,int>>`.
///
/// Layout as read from the globals the container's methods address directly: [measured]
///
/// ```text
/// +0x00  String  current_key      // 0x00ed6650, a 20-byte String mirror
/// +0x14  int     current_value    // 0x00ed6664
/// +0x18  LLNode* current          // 0x00ed6668
/// +0x1c  int     count            // 0x00ed666c
/// +0x20  LLNode* head             // 0x00ed6670
/// ```
///
/// The list is **circular and doubly linked** (`LLNode+0` next, `+4` prev) and
/// `ordered_insert` `0x004d2120` keeps it sorted **ascending by expiry**, so `head` is
/// always the soonest timer. The `current` cursor is not a convenience: `check`
/// `0x00a04b80` reads the expiry through `current_value`, which `seek` `0x004d2340` sets
/// as a side effect, and `remove_current` `0x004c9060` advances it.
///
/// This is script-engine state, not simulation state, so it is implemented in full here.
/// The `Vec` keeps the retail order exactly, with element 0 being `head`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ScriptTimers {
    entries: Vec<Timer>,
    current: Option<usize>,
    /// Set when `add_timer` refused at the cap, mirroring `Error::report` `0x00a2e550`.
    pub overflowed: u32,
}

impl ScriptTimers {
    /// `cmp dword ptr [0x00ed666c], 0x64` at `ScriptTimers::add_timer+0x1b` — a hundred
    /// live timers is the hard cap, and the hundred-and-first is an `Error::report`, not a
    /// silent drop. [measured, `0x00a049fb`]
    pub const MAX_TIMERS: usize = 100;

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// `LinkListBase::count` (`0x00ed666c`).
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// The list in retail order: ascending expiry, `head` first.
    pub fn iter(&self) -> impl Iterator<Item = &Timer> {
        self.entries.iter()
    }

    /// The `current` cursor's entry, i.e. the `current_key` / `current_value` mirror.
    pub fn current(&self) -> Option<&Timer> {
        self.current.and_then(|i| self.entries.get(i))
    }

    /// `LinkListBase::seek` `0x004d2340`. On a hit it moves `current` and returns true; on
    /// a miss it returns false and **leaves `current` where it was** — retail does not
    /// clear the cursor on a failed seek.
    fn seek(&mut self, name: &str) -> Result<bool, HostError> {
        for i in 0..self.entries.len() {
            if string_eq(&self.entries[i].name, name)? {
                self.current = Some(i);
                return Ok(true);
            }
        }
        Ok(false)
    }

    /// `LinkListBase::ordered_insert` `0x004d2120`.
    ///
    /// The walk at `0x004d21a7..0x004d21c2` advances while `new > node->value` and inserts
    /// *before* the first node whose value is `>=` the new one — so equal expiries put the
    /// newest first. A value greater than every node's inserts before `head`, i.e. at the
    /// tail of the circular list, without moving `head`. `current` becomes the new node.
    fn ordered_insert(&mut self, name: &str, expires_at: i32) {
        let at = self
            .entries
            .iter()
            .position(|e| e.expires_at >= expires_at)
            .unwrap_or(self.entries.len());
        self.entries.insert(
            at,
            Timer {
                name: name.to_string(),
                expires_at,
            },
        );
        self.current = Some(at);
    }

    /// `LinkListBase::remove_current` `0x004c9060`: drop `current` and advance the cursor
    /// to its successor, wrapping to `head`. A one-element list clears the whole container
    /// including the cursor.
    fn remove_current(&mut self) {
        let Some(i) = self.current else { return };
        if i >= self.entries.len() {
            return;
        }
        self.entries.remove(i);
        self.current = if self.entries.is_empty() {
            None
        } else {
            Some(i % self.entries.len())
        };
    }

    /// `LinkListBase::remove` `0x004d2230`. Returns whether a node was unlinked.
    ///
    /// Removing a node that is *not* `current` leaves the cursor on the same node — which
    /// in this representation means fixing up its index.
    fn remove(&mut self, name: &str) -> Result<bool, HostError> {
        let mut found = None;
        for i in 0..self.entries.len() {
            if string_eq(&self.entries[i].name, name)? {
                found = Some(i);
                break;
            }
        }
        let Some(i) = found else { return Ok(false) };
        let cur = self.current;
        self.entries.remove(i);
        self.current = if self.entries.is_empty() {
            None
        } else {
            match cur {
                // The cursor node itself went: retail advanced it to the successor.
                Some(c) if c == i => Some(i % self.entries.len()),
                Some(c) if c > i => Some(c - 1),
                other => other.map(|c| c.min(self.entries.len() - 1)),
            }
        };
        Ok(true)
    }

    /// `ScriptTimers::add_timer` `0x00a049e0`.
    ///
    /// `1` on success, `-1` at the cap. An existing timer of the same name is removed
    /// first (`seek` then `remove_current`), so this is a map insert, not a multimap one.
    pub fn add_timer(&mut self, name: &str, expires_at: i32) -> Result<i32, HostError> {
        if self.entries.len() >= Self::MAX_TIMERS {
            self.overflowed = self.overflowed.saturating_add(1);
            return Ok(-1);
        }
        if self.seek(name)? {
            self.remove_current();
        }
        self.ordered_insert(name, expires_at);
        Ok(1)
    }

    /// `ScriptTimers::remove_timer` / the `stop_timer` path: `LinkListBase::remove`.
    pub fn remove_timer(&mut self, name: &str) -> Result<bool, HostError> {
        self.remove(name)
    }

    /// `ScriptTimers::check` `0x00a04b80`.
    ///
    /// `-1` no such timer, `0` not due yet, `1` due — and a due timer is **consumed**
    /// (`remove_current` at `0x00a04bcd`), which is why the shipped scripts re-arm inside
    /// the `if (timer_expired(...))` body.
    ///
    /// The comparison is `now >= expiry` on signed 32-bit `Game::tick`.
    pub fn check(&mut self, name: &str, now: i32) -> Result<i32, HostError> {
        if !self.seek(name)? {
            return Ok(-1);
        }
        let due = self.current().map(|t| t.expires_at).unwrap_or(i32::MAX);
        if now >= due {
            self.remove_current();
            Ok(1)
        } else {
            Ok(0)
        }
    }
}

// ---------------------------------------------------------------------------
// Named constants read out of the handlers
// ---------------------------------------------------------------------------

/// `GameInfo::victory` (`Game+0x38`) values, as the ten `is_victory_*` handlers compare
/// them. The immediate in each handler is listed beside the PDB's `VictoryIndex`
/// enumerator for that number; the two were recovered from independent artefacts.
///
/// **`is_victory_territory` is misnamed.** Builtin 103 (`0x009e52c0`) compares against
/// `7`, and `VictoryIndex` names `7` `VICTORY_POPULATION`. There is no `VICTORY_TERRITORY`
/// enumerator at all. Anyone reading the builtin's *name* to decide which mode it selects
/// gets the wrong mode.
pub mod victory {
    /// `is_victory_standard` `0x009e5250` — `VICTORY_STANDARD`.
    pub const STANDARD: u8 = 0;
    /// `is_victory_sudden_death` `0x009e52a0` — `VICTORY_SUDDEN_DEATH`.
    pub const SUDDEN_DEATH: u8 = 1;
    /// `is_victory_conquest` `0x009e5260` — `VICTORY_CONQUEST`.
    pub const CONQUEST: u8 = 2;
    /// `is_victory_score` `0x009e5290` — `VICTORY_SCORE`.
    pub const SCORE: u8 = 3;
    /// `is_victory_time_limit` `0x009e52d0` — `VICTORY_TIME_LIMIT`.
    pub const TIME_LIMIT: u8 = 4;
    /// `is_victory_musical_chairs` `0x009e5280` — `VICTORY_MUSICAL_CHAIRS`.
    pub const MUSICAL_CHAIRS: u8 = 5;
    /// `is_victory_wonder` `0x009e52e0` — `VICTORY_WONDER`.
    pub const WONDER: u8 = 6;
    /// `is_victory_territory` `0x009e52c0` — the PDB calls `7` `VICTORY_POPULATION`.
    pub const TERRITORY: u8 = 7;
    /// `is_victory_economic` `0x009e5270` — `VICTORY_ECONOMIC`.
    pub const ECONOMIC: u8 = 8;
    /// `is_victory_tech_race` `0x009e52b0` — `VICTORY_TECH_RACE`.
    pub const TECH_RACE: u8 = 9;
}

/// `Leaders` (`0x00e3a390`, stride `0x6eec`) — the first dword of a `LeaderData` is a flag
/// word, and every scenario builtin that takes a `who` gates on the same two bits.
pub mod leader_flag {
    /// Bit 0. `find_unit`, `num_objects_selected`, `valid_object_o` and
    /// `object_type_selected` all require it.
    pub const VALID: u32 = 1;
    /// Bit 1. Required by every one of those **except** `object_type_selected`
    /// (`0x009f055e` tests bit 0 only) — a real asymmetry, not a transcription slip.
    pub const PRESENT: u32 = 2;
}

/// `Game::semaphore` (`BitMask<256>` at `Game+0x814`, bit bytes from `Game+0x820`) bits
/// that scenario builtins test.
pub mod semaphore_bit {
    /// `test byte ptr [Game+0x820], 4` in `object_type_selected` `0x009f0544` and
    /// `num_objects_selected` `0x009f071b`: when set, both refuse with `-1`.
    pub const SELECTION_BLOCKED: u32 = 2;
    /// `is_conquest_scenario` `0x009e6040` reads `(*(u8*)(Game+0x822) >> 1) & 1`, i.e.
    /// `8 * 2 + 1`.
    pub const CONQUEST_SCENARIO: u32 = 17;
}

/// `Objects` band bounds and encodings the handlers hard-code.
pub mod object_band {
    /// `cmp edx, 0xbb7 / ja` in `valid_object_o` `0x009e32c5` — object handles run
    /// `0..=2999`.
    pub const MAX_OBJECT_O: i32 = 0xbb7;
    /// `SubObjectData::x_internal` / `y_internal` are stored XORed with this;
    /// `bubble_text_obj` `0x009ff58b` un-XORs both before handing them to `MessageWin`.
    pub const POSITION_XOR: i32 = 0x0006_3637;
    /// The scan bound in `ScenarioFuncSet::get_type_index` `0x00a034c2` and the inlined
    /// scan in `object_type_selected` `0x009f0528`: 806 type records.
    pub const TYPE_COUNT: i32 = 0x326;
}

/// `ScenarioFuncSet::find_unit` `0x009e2850` acceptance modes, read from the
/// `sub eax, N / je` chain at `0x009e28e0`.
pub mod find_unit_mode {
    /// Accept any live captain of the right type.
    pub const ANY: i32 = 0;
    /// `SubObjectData::is_valid_unit` (vtable `+0x08`) **and** `ObjectData::is_on_map`
    /// (`+0xbc`). This is the mode the `find_unit` builtin passes.
    pub const ON_MAP: i32 = 1;
    /// `!ObjectData::is_on_map` **and** `SubObjectData::is_active` (`+0x4c`).
    pub const OFF_MAP_ACTIVE: i32 = 2;
}

/// The five object predicates the `find_unit` scan and the selection scan call through the
/// object vtable, gathered into one probe so a host answers them together.
///
/// Slot names are from `schema/types.json`; the slot *numbers* are the ones the handlers
/// index. [measured]
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ObjectProbe {
    /// `SubObjectData+0x08 & 1` — the raw liveness bit every scan tests before touching
    /// the vtable (`0x009e28a7`, `0x0070f9aa`, `0x009e32e6`).
    pub alive: bool,
    /// `ObjectData::is_captain`, vtable `+0xe8`.
    pub is_captain: bool,
    /// `SubObjectData::is_valid_unit`, vtable `+0x08`.
    pub is_valid_unit: bool,
    /// `ObjectData::is_on_map`, vtable `+0xbc`.
    pub is_on_map: bool,
    /// `SubObjectData::is_active`, vtable `+0x4c`.
    pub is_active: bool,
    /// `SubObjectData::is_build`, vtable `+0x20`.
    pub is_build: bool,
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

/// Lowest and highest `ScenarioFuncSet` index this module answers for.
pub const SCENARIO_MIN_INDEX: u32 = 31;

/// The indices [`call_scenario`] implements. A measured coverage number, not a claimed
/// one: the dispatch `match` and this list are kept in step by a test that walks both.
pub fn implemented_indices() -> std::collections::BTreeSet<u32> {
    [
        77, 78, 79, // the ScriptTimers subsystem
        94, 95, // GameInfo::flags / rush_rules
        96, 97, 98, 99, 100, 101, 102, 103, 104, 105, // GameInfo::victory
        147, // Game::semaphore bit 17
        298, // Game::tick
        311, // Units::lists scan
        390, 392, // the local selection group
        783, // MessageWin
    ]
    .into_iter()
    .collect()
}

fn arg(args: &[Value], i: usize) -> Value {
    args.get(i).cloned().unwrap_or(Value::Null)
}

fn str_arg(args: &[Value], i: usize, what: &'static str) -> Result<String, HostError> {
    arg(args, i)
        .as_string()
        .map_err(|_| HostError::BadArgs(what))
}

/// Dispatch one `ScenarioFuncSet` builtin.
///
/// Returns `None` when `decl` is not one of the indices this module covers, so a host can
/// chain it after [`crate::builtins::call_util`] and fall through to its own table:
///
/// ```ignore
/// fn call(&mut self, decl: &BuiltinDecl, args: &[Value]) -> HostResult {
///     if let Some(r) = don_bhs::builtins::call_util(self, decl, args) { return r; }
///     if let Some(r) = don_bhs::scenario::call_scenario(self, decl, args) { return r; }
///     Err(HostError::Unimplemented)
/// }
/// ```
pub fn call_scenario<H: Host + ?Sized>(
    host: &mut H,
    decl: &BuiltinDecl,
    args: &[Value],
) -> Option<HostResult> {
    if !implemented_indices().contains(&decl.index) {
        return None;
    }
    Some(dispatch(host, decl, args))
}

fn dispatch<H: Host + ?Sized>(host: &mut H, decl: &BuiltinDecl, args: &[Value]) -> HostResult {
    match decl.index {
        // ---- ScriptTimers ----------------------------------------------------
        //
        // set_timer(timer_id, seconds) `0x009e4bc0`:
        //   msg = timer_id                                       0x009e4bcd
        //   if (seconds <= 0)          return -1                 0x009e4bd9
        //   if (timer_id.curr_len == 0) return -1                0x009e4be0
        //   tail-jmp add_timer(msg, Game::tick + seconds)        0x009e4bf4
        // Both refusals are -1 and the order is seconds-then-length, so
        // `set_timer("", 0)` and `set_timer("", 5)` are the same answer for
        // different reasons.
        77 => {
            let name = str_arg(args, 0, "set_timer: timer_id is not a string")?;
            let seconds = arg(args, 1).as_int();
            if seconds <= 0 {
                return Ok(Value::Int(-1));
            }
            if name.is_empty() {
                return Ok(Value::Int(-1));
            }
            // `add eax, ecx` on two ints: wrapping, not saturating.
            let expires_at = host.game_seconds()?.wrapping_add(seconds);
            let t = host.script_timers()?;
            Ok(Value::Int(t.add_timer(&name, expires_at)?))
        }
        // stop_timer(timer_id) `0x009e4c10`: `remove(msg) ? 1 : -1`. Note there is no
        // empty-name guard here, unlike set_timer — `stop_timer("")` really does search
        // for a timer named "".
        78 => {
            let name = str_arg(args, 0, "stop_timer: timer_id is not a string")?;
            let t = host.script_timers()?;
            Ok(Value::Int(if t.remove_timer(&name)? { 1 } else { -1 }))
        }
        // timer_expired(timer_id) `0x009e4c80`: `check(msg, Game::tick)`.
        //
        // `re/decomp-all/009e4c80.c` types this `void` and drops the second argument
        // entirely; the tail call at `0x009e4c9c` passes `Game+0x560` and returns
        // `ScriptTimers::check`'s EAX. The declaration in `schema/bhs-builtins.json`
        // agrees with the disassembly: `int`.
        79 => {
            let name = str_arg(args, 0, "timer_expired: timer_id is not a string")?;
            let now = host.game_seconds()?;
            let t = host.script_timers()?;
            Ok(Value::Int(t.check(&name, now)?))
        }

        // ---- GameInfo scalars ------------------------------------------------
        // get_is_no_nation_powers() `0x009e5230`: `(*(u8*)(Game+0x20) >> 2) & 1`.
        // `Game+0x20` is `GameInfo::flags` (`GameInfo` is `Game+0x0C`, `flags` is +0x14),
        // read as a byte, so only bits 0..7 are reachable from here.
        94 => Ok(Value::Int(((host.game_info_flags()? >> 2) & 1) as i32)),
        // get_rush_rules() `0x009e5240`: `movzx eax, byte [Game+0x32]` — GameInfo+0x26,
        // a `RushRulesIndex` (`RUSH_STANDARD`=0 .. `RUSH_30_MINUTES`=14).
        95 => Ok(Value::Int(host.game_info_rush_rules()? as i32)),
        // is_victory_*() `0x009e5250`..`0x009e52e0`: `sete` on `GameInfo::victory`.
        96..=105 => {
            let want = match decl.index {
                96 => victory::STANDARD,
                97 => victory::CONQUEST,
                98 => victory::ECONOMIC,
                99 => victory::MUSICAL_CHAIRS,
                100 => victory::SCORE,
                101 => victory::SUDDEN_DEATH,
                102 => victory::TECH_RACE,
                103 => victory::TERRITORY,
                104 => victory::TIME_LIMIT,
                _ => victory::WONDER,
            };
            Ok(Value::Int((host.game_info_victory()? == want) as i32))
        }
        // is_conquest_scenario() `0x009e6040`: `(*(u8*)(Game+0x822) >> 1) & 1`.
        147 => Ok(Value::Int(
            host.game_semaphore_bit(semaphore_bit::CONQUEST_SCENARIO)? as i32,
        )),
        // time_sec() `0x009ead40` — twelve bytes: `Game::tick` (`Game+0x560`) verbatim.
        // The PDB calls the field `tick`; `docs/mechanics/victory-score.md` already
        // establishes it counts game seconds, which is what makes `set_timer`'s
        // `tick + seconds` type-correct.
        298 => Ok(Value::Int(host.game_seconds()?)),

        // ---- find_unit -------------------------------------------------------
        311 => find_unit(host, args),
        // ---- the local selection group ---------------------------------------
        390 => object_type_selected(host, args),
        392 => num_objects_selected(host, args),
        // ---- presentation ----------------------------------------------------
        783 => bubble_text_obj(host, args),

        _ => Err(HostError::Unimplemented),
    }
}

/// `who` is 1-based in every scenario builtin that takes one; the handler's first act is
/// `dec`, and the bound is then an **unsigned** `> 7`, so `who = 0` becomes `0xffffffff`
/// and is refused. [measured: `0x009ebe22`/`0x009ebe75`, `0x009f04f3`/`0x009f054d`,
/// `0x009f06f8`, `0x009ff55c`]
fn who_zero_based(v: i32) -> Option<i32> {
    let who0 = v.wrapping_sub(1);
    (0..=7).contains(&who0).then_some(who0)
}

/// `ScenarioFuncSet::find_unit` builtin 311, `0x009ebe10`, and the scan it calls,
/// `ScenarioFuncSet::find_unit` `0x009e2850`.
///
/// The outer handler is a cursor plus five refusals; the inner is a wrapping scan of the
/// owner's `Units::lists` band (`0x00c0aec0`, stride `0x1c` per owner, count at
/// `Objects+0x15c+who0*4`).
fn find_unit<H: Host + ?Sized>(host: &mut H, args: &[Value]) -> HostResult {
    let who_raw = arg(args, 0).as_int();
    let type_name = str_arg(args, 1, "find_unit: unit_type is not a string")?;

    // `[0x00cc2214]`, a file-static search cursor clamped at zero and read *before* any
    // refusal path. It is not per-type and not per-player: consecutive find_unit calls in
    // one script share it, which is why general_powers.bhs walking thirteen leaders in one
    // frame does not restart from object 0 each time.
    let cursor = host.find_unit_cursor()?.max(0);
    host.set_find_unit_cursor(cursor)?;

    let type_index = if type_name.is_empty() {
        // An empty unit_type is "any unit", encoded as -1 — the `or edi, -1` at
        // `0x009ebe9a`, *not* a refusal.
        -1
    } else {
        let ti = host.type_index_by_name(&type_name)?;
        if ti < 0 {
            return Ok(Value::Int(-1));
        }
        if !host.type_is_unit_type(ti)? {
            return Ok(Value::Int(-1));
        }
        ti
    };

    let Some(who0) = who_zero_based(who_raw) else {
        return Ok(Value::Int(-1));
    };
    let flags = host.leader_flags(who0)?;
    if flags & leader_flag::VALID == 0 || flags & leader_flag::PRESENT == 0 {
        return Ok(Value::Int(-1));
    }

    let found = find_unit_scan(host, who0, type_index, cursor, find_unit_mode::ON_MAP)?;
    if found < 0 {
        return Ok(Value::Int(-1));
    }
    host.set_find_unit_cursor(found)?;
    Ok(Value::Int(found))
}

/// `ScenarioFuncSet::find_unit(type_index, start, mode)` `0x009e2850`, `who0` in `ECX`.
///
/// ```text
///   n = Objects+0x15c+who0*4                       // the band's high-water count
///   if (start >= n || start < 0) start = 0         // 0x009e286b..0x009e2874
///   i = start + 1                                  // the scan begins *after* start
///   do {
///     idx = (i < n) ? i : 0                        // 0x009e2897 cmovl
///     ...
///     i = idx + 1
///   } while (i != start + 1)
///   return -1
/// ```
///
/// Two facts worth not re-deriving: the scan starts at `start + 1`, so a repeated call
/// with an unchanged cursor finds the *next* match rather than the same object; and the
/// wrap sentinel is compared against `start + 1`, so index `start` itself is the last
/// candidate examined, not a skipped one.
pub fn find_unit_scan<H: Host + ?Sized>(
    host: &mut H,
    who0: i32,
    type_index: i32,
    start: i32,
    mode: i32,
) -> Result<i32, HostError> {
    let n = host.unit_band_count(who0)?;
    if n <= 0 {
        // With n <= 0 the cmovl never fires, idx is 0 forever and `i` never returns to
        // `first`; retail would spin. Refuse rather than reproduce a hang.
        return Err(HostError::BadArgs(
            "find_unit: empty unit band; retail 0x009e2850 does not terminate here",
        ));
    }
    let start = if start >= n || start < 0 { 0 } else { start };
    let first = start + 1;
    let mut i = first;
    loop {
        let idx = if i < n { i } else { 0 };
        let p = host.unit_band_probe(who0, idx)?;
        // Three gates in the order the body applies them, each short-circuiting the next:
        // the raw liveness bit and `ObjectData::is_captain` (`0x009e28a7`, `0x009e28b3`);
        // the type filter, skipped entirely when `type_index < 0` (`0x009e28c1`); then the
        // mode predicate (`0x009e28e0`).
        let mut accept = p.alive && p.is_captain;
        if accept && type_index >= 0 {
            accept = host.unit_band_is_type(who0, idx, type_index)?;
        }
        if accept {
            accept = match mode {
                find_unit_mode::ANY => true,
                find_unit_mode::ON_MAP => p.is_valid_unit && p.is_on_map,
                find_unit_mode::OFF_MAP_ACTIVE => !p.is_on_map && p.is_active,
                // The `sub/je` chain falls through to "reject" for any other value.
                _ => false,
            };
        }
        if accept {
            return Ok(idx);
        }
        i = idx + 1;
        if i == first {
            return Ok(-1);
        }
    }
}

/// `ScenarioFuncSet::object_type_selected` builtin 390, `0x009f04e0`.
///
/// Answers "does player `who` have an object of this type selected **right now**". The
/// selection it reads is `[0x00e8d444] + Console+0x2a0 * 0x9f0`, the *local* console's
/// select group, and the handler refuses unless that group's owner byte (`GroupData+0x4a`)
/// equals `who - 1`. That makes this builtin a function of local UI state, not of shared
/// simulation state — a script branching on it is not reproducible from a replay alone.
fn object_type_selected<H: Host + ?Sized>(host: &mut H, args: &[Value]) -> HostResult {
    let who_raw = arg(args, 0).as_int();
    let type_name = str_arg(args, 1, "object_type_selected: object_type is not a string")?;
    if type_name.is_empty() {
        return Ok(Value::Int(-1));
    }
    // `String::generate_hashes` at `0x009f0501` is a comparison accelerator, not a
    // semantic step; see `string_eq`.
    let type_index = host.type_index_by_name(&type_name)?;
    if type_index < 0 {
        return Ok(Value::Int(-1));
    }
    if host.game_semaphore_bit(semaphore_bit::SELECTION_BLOCKED)? {
        return Ok(Value::Int(-1));
    }
    let Some(who0) = who_zero_based(who_raw) else {
        return Ok(Value::Int(-1));
    };
    // Bit 0 only. `num_objects_selected`, four instructions away, also requires bit 1.
    if host.leader_flags(who0)? & leader_flag::VALID == 0 {
        return Ok(Value::Int(-1));
    }
    if host.selection_group_owner()? != who0 {
        return Ok(Value::Int(0));
    }
    let members = host.selection_group_members()?;
    if members.is_empty() {
        return Ok(Value::Int(0));
    }
    for o in members {
        if !host.object_band_is_type(who0, o, type_index)? {
            continue;
        }
        let p = host.object_band_probe(who0, o)?;
        // `0x009f0617`: a matching non-building answers yes immediately; a matching
        // building answers with `is_active`, and **returns** either way rather than
        // continuing the scan. A selection holding an unfinished Barracks and a finished
        // one therefore answers on whichever comes first in the group.
        return Ok(Value::Int(if !p.is_build { 1 } else { p.is_active as i32 }));
    }
    Ok(Value::Int(0))
}

/// `ScenarioFuncSet::num_objects_selected` builtin 392, `0x009f06f0`.
///
/// Same five refusals as [`object_type_selected`] except that it also requires
/// [`leader_flag::PRESENT`], then returns `GroupData::get_num_cap_const` `0x0070f960` —
/// the count of members that are still alive and `ObjectData::is_captain`, which is *not*
/// the same as the group's raw `+0xc` count.
fn num_objects_selected<H: Host + ?Sized>(host: &mut H, args: &[Value]) -> HostResult {
    let Some(who0) = who_zero_based(arg(args, 0).as_int()) else {
        return Ok(Value::Int(-1));
    };
    let flags = host.leader_flags(who0)?;
    if flags & leader_flag::VALID == 0 || flags & leader_flag::PRESENT == 0 {
        return Ok(Value::Int(-1));
    }
    if host.game_semaphore_bit(semaphore_bit::SELECTION_BLOCKED)? {
        return Ok(Value::Int(-1));
    }
    if host.selection_group_owner()? != who0 {
        return Ok(Value::Int(0));
    }
    // The band `GroupData::get_num_cap_const` indexes is `[0x00c0ab84 + owner*0x1c]`,
    // which is a *different* base from `Objects` (`0x00c0618c`) and from `Units::lists`
    // (`0x00c0aec0`) and has not been identified. The loop itself is
    //   n = group->count; for each member, if !(alive && is_captain) n--
    // and it is reproduced here over the object band, which is the same predicate on the
    // same handles. If a host's two bands can disagree, that is the divergence to look at.
    let members = host.selection_group_members()?;
    let mut n = members.len() as i32;
    for o in members {
        let p = host.object_band_probe(who0, o)?;
        if !(p.alive && p.is_captain) {
            n -= 1;
        }
    }
    Ok(Value::Int(n))
}

/// `ScenarioFuncSet::bubble_text_obj` builtin 783, `0x009ff550`.
///
/// `valid_object_o` `0x009e32a0` inline, then `MessageWin::add_bubble_message`
/// `0x007e7e20` with the object's un-XORed internal position and the *local display
/// player* (`Console+0x298`). Returns `1`, or `-1` when the handle does not resolve.
///
/// This is presentation: the only state it writes is a `MessageWin`. It is here because
/// `general_powers.bhs`'s last statement is a call to it, and a script that cannot make
/// its final call has not run.
fn bubble_text_obj<H: Host + ?Sized>(host: &mut H, args: &[Value]) -> HostResult {
    let text = str_arg(args, 0, "bubble_text_obj: str_text is not a string")?;
    let who_raw = arg(args, 1).as_int();
    let o = arg(args, 2).as_int();

    let Some(who0) = who_zero_based(who_raw) else {
        return Ok(Value::Int(-1));
    };
    let flags = host.leader_flags(who0)?;
    if flags & leader_flag::VALID == 0 || flags & leader_flag::PRESENT == 0 {
        return Ok(Value::Int(-1));
    }
    if !(0..=object_band::MAX_OBJECT_O).contains(&o) {
        return Ok(Value::Int(-1));
    }
    if !host.object_band_probe(who0, o)?.alive {
        return Ok(Value::Int(-1));
    }
    let (xi, yi) = host.object_band_position_internal(who0, o)?;
    let x = xi ^ object_band::POSITION_XOR;
    let y = yi ^ object_band::POSITION_XOR;
    let display = host.local_display_player()?;
    host.add_bubble_message(&text, x, y, display)?;
    Ok(Value::Int(1))
}

// ---------------------------------------------------------------------------
// A host that answers the cohort from an explicit image
// ---------------------------------------------------------------------------

/// The `Game` scalars the twelve zero-argument gates read, in one place.
///
/// This is an *image*, not a simulation: a caller fills it from wherever it knows the
/// truth (a save game, a scenario file, `don-sim`). Every field names the retail address
/// it stands for so a bridge cannot connect the wrong one.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GameImage {
    /// `Game::tick` `Game+0x560`, game seconds.
    pub tick: i32,
    /// `GameInfo::flags` `Game+0x20` (`GameInfo+0x14`).
    pub info_flags: u32,
    /// `GameInfo::rush_rules` `Game+0x32` (`GameInfo+0x26`), a `RushRulesIndex`.
    pub rush_rules: u8,
    /// `GameInfo::victory` `Game+0x38` (`GameInfo+0x2c`), a `VictoryIndex`.
    pub victory: u8,
    /// `Game::semaphore` `Game+0x814`, the 32 bit-bytes from `Game+0x820`.
    pub semaphore: [u8; 32],
}

impl GameImage {
    pub fn semaphore_bit(&self, bit: u32) -> bool {
        let b = (bit / 8) as usize;
        b < self.semaphore.len() && self.semaphore[b] & (1 << (bit % 8)) != 0
    }

    pub fn set_semaphore_bit(&mut self, bit: u32, on: bool) {
        let b = (bit / 8) as usize;
        if b >= self.semaphore.len() {
            return;
        }
        let m = 1u8 << (bit % 8);
        if on {
            self.semaphore[b] |= m;
        } else {
            self.semaphore[b] &= !m;
        }
    }
}

/// One object as the scenario builtins interrogate it.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ObjectImage {
    pub probe: ObjectProbe,
    /// The index the object's `ptype` occupies in the 806-entry type array — what
    /// `SubObject::is(type_index, 0)` answers against.
    pub type_index: i32,
    /// `SubObjectData::x_internal` / `y_internal` **as stored**, i.e. already XORed with
    /// [`object_band::POSITION_XOR`].
    pub x_internal: i32,
    pub y_internal: i32,
}

/// An explicit image of everything outside `ScenarioData` that the cohort reads.
///
/// It exists so a shipped script can be *run* without `don-sim`, and so the guard logic
/// above is exercised by tests rather than asserted about. It is a fixture, not a model of
/// the simulation: nothing here advances, decays or interacts.
///
/// # One band, two retail symbols
///
/// The `find_unit` scan indexes `Units::lists[who0]` (`0x00c0aec0`, stride `0x1c`) while
/// `valid_object_o` and `object_type_selected` index `Objects::lists[who0]`
/// (`[0x00c0618c] + 0x14 + who0*0x1c`). Those are two distinct symbols and this lane did
/// **not** prove they alias. What is established is that they must share a slot space:
/// `general_powers.bhs` assigns `o = find_unit(1, "Alexander")` — a `Units::lists` band
/// index — and passes it straight to `bubble_text_obj`, which resolves it through
/// `Objects::lists`. So the image keeps one map keyed by `(who0, handle)` and answers both
/// accessors from it. A host that can distinguish the two arrays should say so rather than
/// inherit this simplification.
#[derive(Debug, Clone, Default)]
pub struct ScenarioWorldImage {
    /// `Leaders` `0x00e3a390` stride `0x6eec`, first dword, indexed by `who - 1`.
    pub leader_flags: [u32; 8],
    /// `TypeData+0x60` for each of the 806 type records, in array order. Comparison is
    /// [`string_eq`].
    pub type_names: Vec<String>,
    /// Which of those indices `TypeData::is_unit_type` accepts. The devirtualised form the
    /// binary inlines at `0x009ebe5d` is `0x32 <= TypeData+4 < 0x19e`; a host that knows
    /// the type numbers can populate this from that range instead of by name.
    pub unit_type_indices: std::collections::BTreeSet<i32>,
    /// The per-owner object slots, keyed `(who0, handle)`. Absent means an empty slot,
    /// which every predicate reads as not-alive.
    pub objects: BTreeMap<(i32, i32), ObjectImage>,
    /// `Objects+0x15c+who0*4` — the band high-water `find_unit`'s scan wraps against. It
    /// is a count, not a maximum handle, and it is what makes the scan terminate.
    pub unit_band_count: BTreeMap<i32, i32>,
    /// `GroupData+0x4a` of the local console's select group.
    pub selection_owner: i32,
    /// `GroupData+0x8cc`, the `short[]` member handles.
    pub selection: Vec<i32>,
    /// `Console+0x298`.
    pub local_display_player: i32,
}

impl ScenarioWorldImage {
    /// Place one object at `(who0, handle)` and widen the band high-water to cover it.
    pub fn put_object(&mut self, who0: i32, handle: i32, o: ObjectImage) -> &mut Self {
        self.objects.insert((who0, handle), o);
        let e = self.unit_band_count.entry(who0).or_insert(0);
        *e = (*e).max(handle + 1);
        self
    }
}

/// A [`Host`] that implements the utility function sets, the [`ScriptTimers`] subsystem,
/// and the twenty-one `ScenarioFuncSet` entries in this module — the rest poison.
///
/// This is the host a shipped scenario script can actually run on.
#[derive(Default)]
pub struct ScenarioHost {
    /// The four utility `FuncSet`s, including the shared `GameAccess::game_random` stream.
    pub util: crate::builtins::UtilHost,
    /// `ScenarioData::timers` `0x00ed6650`.
    pub timers: ScriptTimers,
    /// `Game` scalars.
    pub game: GameImage,
    /// Everything else the cohort reads. `None` means "this host does not model the
    /// world", and every builtin that needs it poisons rather than answering.
    pub world: Option<ScenarioWorldImage>,
    /// `[0x00cc2214]`, the `find_unit` search cursor.
    pub find_cursor: i32,
    /// Everything `bubble_text_obj` handed to `MessageWin::add_bubble_message`, in order:
    /// `(text, x, y, display_player)`.
    pub bubbles: Vec<(String, i32, i32, i32)>,
}

impl ScenarioHost {
    pub fn new() -> ScenarioHost {
        ScenarioHost::default()
    }

    fn world(&self) -> Result<&ScenarioWorldImage, HostError> {
        self.world.as_ref().ok_or(HostError::Unimplemented)
    }
}

impl Host for ScenarioHost {
    fn call(&mut self, decl: &BuiltinDecl, args: &[Value]) -> HostResult {
        if let Some(r) = crate::builtins::call_util(self, decl, args) {
            return r;
        }
        if let Some(r) = call_scenario(self, decl, args) {
            return r;
        }
        Err(HostError::Unimplemented)
    }

    fn game_random(&mut self, lo: i32, hi: i32) -> Result<i32, HostError> {
        self.util.game_random(lo, hi)
    }
    fn game_random_step(&mut self) -> Result<u32, HostError> {
        self.util.game_random_step()
    }
    fn game_random_seed(&self) -> Result<u32, HostError> {
        self.util.game_random_seed()
    }
    fn set_game_random_seed(&mut self, s: u32) -> Result<(), HostError> {
        self.util.set_game_random_seed(s)
    }
    fn script_print(&mut self, s: &str, newline: bool) -> Result<(), HostError> {
        self.util.script_print(s, newline)
    }

    fn game_seconds(&mut self) -> Result<i32, HostError> {
        Ok(self.game.tick)
    }
    fn game_info_flags(&mut self) -> Result<u32, HostError> {
        Ok(self.game.info_flags)
    }
    fn game_info_rush_rules(&mut self) -> Result<u8, HostError> {
        Ok(self.game.rush_rules)
    }
    fn game_info_victory(&mut self) -> Result<u8, HostError> {
        Ok(self.game.victory)
    }
    fn game_semaphore_bit(&mut self, bit: u32) -> Result<bool, HostError> {
        Ok(self.game.semaphore_bit(bit))
    }
    fn script_timers(&mut self) -> Result<&mut ScriptTimers, HostError> {
        Ok(&mut self.timers)
    }

    fn find_unit_cursor(&mut self) -> Result<i32, HostError> {
        Ok(self.find_cursor)
    }
    fn set_find_unit_cursor(&mut self, v: i32) -> Result<(), HostError> {
        self.find_cursor = v;
        Ok(())
    }

    fn leader_flags(&mut self, who0: i32) -> Result<u32, HostError> {
        let w = self.world()?;
        w.leader_flags
            .get(who0 as usize)
            .copied()
            .ok_or(HostError::BadArgs("leader_flags: who0 out of 0..8"))
    }

    fn type_index_by_name(&mut self, name: &str) -> Result<i32, HostError> {
        let names = self.world()?.type_names.clone();
        for (i, n) in names.iter().enumerate() {
            if i as i32 >= object_band::TYPE_COUNT {
                break;
            }
            if string_eq(n, name)? {
                return Ok(i as i32);
            }
        }
        Ok(-1)
    }

    fn type_is_unit_type(&mut self, type_index: i32) -> Result<bool, HostError> {
        Ok(self.world()?.unit_type_indices.contains(&type_index))
    }

    fn unit_band_count(&mut self, who0: i32) -> Result<i32, HostError> {
        Ok(self
            .world()?
            .unit_band_count
            .get(&who0)
            .copied()
            .unwrap_or(0))
    }

    fn unit_band_probe(&mut self, who0: i32, idx: i32) -> Result<ObjectProbe, HostError> {
        self.object_band_probe(who0, idx)
    }

    fn unit_band_is_type(
        &mut self,
        who0: i32,
        idx: i32,
        type_index: i32,
    ) -> Result<bool, HostError> {
        self.object_band_is_type(who0, idx, type_index)
    }

    fn object_band_probe(&mut self, who0: i32, o: i32) -> Result<ObjectProbe, HostError> {
        Ok(self
            .world()?
            .objects
            .get(&(who0, o))
            .map(|x| x.probe)
            .unwrap_or_default())
    }

    fn object_band_is_type(
        &mut self,
        who0: i32,
        o: i32,
        type_index: i32,
    ) -> Result<bool, HostError> {
        Ok(self
            .world()?
            .objects
            .get(&(who0, o))
            .map(|x| x.type_index == type_index)
            .unwrap_or(false))
    }

    fn object_band_position_internal(
        &mut self,
        who0: i32,
        o: i32,
    ) -> Result<(i32, i32), HostError> {
        self.world()?
            .objects
            .get(&(who0, o))
            .map(|x| (x.x_internal, x.y_internal))
            .ok_or(HostError::BadArgs("object_band_position: no such handle"))
    }

    fn selection_group_owner(&mut self) -> Result<i32, HostError> {
        Ok(self.world()?.selection_owner)
    }

    fn selection_group_members(&mut self) -> Result<Vec<i32>, HostError> {
        Ok(self.world()?.selection.clone())
    }

    fn local_display_player(&mut self) -> Result<i32, HostError> {
        Ok(self.world()?.local_display_player)
    }

    fn add_bubble_message(
        &mut self,
        text: &str,
        x: i32,
        y: i32,
        who: i32,
    ) -> Result<(), HostError> {
        self.bubbles.push((text.to_string(), x, y, who));
        Ok(())
    }
}
