#!/usr/bin/env python3
"""Generate crates/don-rules/src/offsets.rs from schema/bindings.json.

The offsets are recovered mechanically from the binary's descriptor/visitor binding
sites (see re/scripts/ExtractDescriptors.java). This generator is deliberately dumb:
it renames nothing and infers nothing. Every constant here traces to a call site
address recorded in bindings.json.

Run:  python3 re/scripts/gen_offsets.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "schema" / "bindings.json"
OUT = ROOT / "crates" / "don-rules" / "src" / "offsets.rs"

RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do",
    "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
}


def ident(name: str) -> str:
    """Turn a rule name into a SCREAMING_SNAKE Rust identifier, losslessly enough."""
    s = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_").upper()
    if not s:
        s = "UNNAMED"
    if s[0].isdigit():
        s = "N" + s
    if s.lower() in RUST_KEYWORDS:
        s += "_"
    return s


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}; run the ExtractDescriptors sweep first", file=sys.stderr)
        return 1
    bindings = json.loads(SRC.read_text())

    by_func: dict[str, list[dict]] = {}
    for b in bindings:
        by_func.setdefault(b["func"], []).append(b)

    lines = [
        "//! Field offsets recovered from the binary's rule-binding call sites.",
        "//!",
        "//! GENERATED by `re/scripts/gen_offsets.py` from `schema/bindings.json`.",
        "//! Do not edit by hand; re-run the generator instead.",
        "//!",
        "//! Each module corresponds to one loader function in `riseofnations.exe`, named by",
        "//! its entry address. Constants are byte offsets from the base pointer that the",
        "//! binding site pushes. **[measured]** -- every value traces to a call site address",
        "//! in `bindings.json`.",
        "//!",
        "//! Offsets may be negative: some binding sites use a base register that points into",
        "//! the middle of a structure, so these are `isize`, not `usize`.",
        "//!",
        "//! No type information is asserted here. The descriptor's type tag is recovered but",
        "//! its meaning outside two validated loaders is **[unverified]** -- a hypothesis that",
        "//! it selects the value parser was tested against the shipped XML unit words and",
        "//! *refuted*. Until that is settled, these are addresses, not typed fields.",
        "",
        "#![allow(dead_code)]",
        "",
    ]

    total = 0
    for func in sorted(by_func):
        recs = sorted(by_func[func], key=lambda r: r["field_off"])
        # a name can legitimately be bound twice; keep the first and note collisions
        seen: dict[str, int] = {}
        emitted = []
        for r in recs:
            key = ident(r["name"])
            if key in seen:
                continue
            seen[key] = r["field_off"]
            emitted.append((key, r))
        mod = func.lower()
        lines.append(f"/// {len(emitted)} bindings recovered from `{func}`.")
        lines.append(f"pub mod {mod} {{")
        for key, r in emitted:
            lines.append(f"    /// `{r['name']}` — bound at {r['ref_ea']}")
            lines.append(f"    pub const {key}: isize = {r['field_off']};")
        lines.append("}")
        lines.append("")
        total += len(emitted)

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {total} constants across {len(by_func)} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
