#!/usr/bin/env python3
"""Generate `crates/don-rules/src/rules.rs` from `docs/derivation/rules-constants.json`.

The JSON is the recovered schema of the engine's `Rules` value block: 719 records (717
distinct struct offsets; two names were recovered twice from two binder sites), 845 slots,
each with the struct offset, the parse mode the loader uses (`_wtoi` = scale 1, or
`RString::AsScaled(scale)` with scale 100 / 192 / 256), the shipped `rules.xml` text and
the integer the engine stores.

What this emits, and why in this shape:

* `Rules { raw: [i32; 848] }` mirrors the engine's own layout — one contiguous dword block
  at `Rules + 0`, the XML section object sitting immediately after it at `Rules + 0xD40`.
  A live capture of that block (`schema/live/rules-block-*.txt`) drops straight in.
* One accessor per named field, so call sites read `r.gather_rate()` instead of
  `raw[636 / 4]`. Array fields take an index.
* `SLOTS`, the (text, scale, stored) triples, so the tokenizer's tests can assert against
  the whole shipped corpus rather than against a hand-picked sample.

Run: `python3 re/scripts/gen_rules.py > crates/don-rules/src/rules.rs`
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "docs", "derivation", "rules-constants.json")

RUST_KW = {
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
    "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while", "async", "await", "abstract", "become", "box", "do",
    "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
    "union", "gen",
}


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def short(s, n=64):
    s = " ".join(s.split())
    return s if len(s) <= n else s[: n - 1] + "\u2026"


def main():
    with open(SRC) as fh:
        recs = json.load(fh)

    # Two names appear twice, both times at the same offset from a second binder site.
    by_off = {}
    for r in recs:
        prev = by_off.get(r["offset"])
        if prev is None:
            by_off[r["offset"]] = r
        else:
            prev.setdefault("extra_binders", []).append(r["binder_ea"])
            assert prev["name"] == r["name"] and prev["count"] == r["count"], r["name"]
    fields = [by_off[o] for o in sorted(by_off)]

    max_off = max(e["offset"] for r in recs for e in r["entries"])
    dwords = max_off // 4 + 1

    shipped = [None] * dwords
    slots = []
    for r in fields:
        scale = r["scale"] if r["parser"] == "scaled" else (1 if r["parser"] == "wtoi" else 0)
        for e in r["entries"]:
            if e["stored"] is not None:
                shipped[e["offset"] // 4] = e["stored"]
            if e["stored"] is not None and e["xml_value"] is not None and scale:
                slots.append((r["name"], e["index"], e["offset"], scale, e["xml_value"], e["stored"]))
    unrecovered = [i for i, v in enumerate(shipped) if v is None]

    out = sys.stdout.write
    out(f'''//! The engine's `Rules` value block, by name.
//!
//! GENERATED by `re/scripts/gen_rules.py` from `docs/derivation/rules-constants.json`.
//! Do not edit by hand; re-run the generator instead.
//!
//! # What this is
//!
//! `Rules::Load` (`0x00569A90`\u2013`0x0057016F`) fills a flat block of `i32` at offset 0 of the
//! `RULES` singleton, one slot per `<CONSTANTS>` element, arrays laid out contiguously; the
//! XML section object it read them from sits immediately after the block at `Rules + 0xD40`
//! (= {dwords} dwords). Every scalar site is one of two calls \u2014 `0x0057FA60(name)`, which
//! parses with `_wtoi` (scale 1), or `0x0057F950(name, scale)`, which parses with
//! `RString::AsScaled` (`0x00A1D110`) at a **compile-time per-field** scale of 100, 192 or
//! 256. Array entries are all `_wtoi`.
//!
//! [`Rules`] therefore holds the block itself, not a struct of {len(fields)} separate fields: that
//! is the engine's own layout, so a live capture of `[[0x00C061E4]]` deserialises by
//! `copy_from_slice` and an offset in a disassembly listing indexes it directly.
//!
//! # Provenance
//!
//! **[measured]** \u2014 offsets and parse modes from the loader's own call sites; shipped values
//! from `ron-data/rules.xml` as the engine stores them. **828 of 834 of these constants were
//! confirmed byte-for-byte against a running match's `RULES` object** (see
//! `docs/provenance-ledger.md`, "Live-process validation"); the six that differed were
//! missing scale annotations, since corrected. Derivation: `docs/derivation/economy.md`.
//!
//! Nothing here is verified in the proof-assistant sense.

#![allow(dead_code)]

/// Size of the value block, in dwords. `0xD40 / 4` is where the XML section object begins,
/// and the highest recovered slot is `{max_off}`.
pub const RULES_DWORDS: usize = {dwords};

/// The `Rules` value block: `RULES + 0 ..= RULES + {max_off}`, as the engine stores it.
///
/// Indexing is by **dword**, so a byte offset seen in a disassembly is `off / 4`. Use the
/// named accessors; `raw` is public so a live capture can be loaded wholesale.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Rules {{
    pub raw: [i32; RULES_DWORDS],
}}

impl Default for Rules {{
    /// The **shipped** values, not zeros \u2014 a zeroed rules block is not a state the engine
    /// can be in, and several fields are divisors.
    fn default() -> Self {{
        Rules {{ raw: SHIPPED }}
    }}
}}

impl Rules {{
    /// The block as `rules.xml` ships it.
    pub const fn shipped() -> Rules {{
        Rules {{ raw: SHIPPED }}
    }}

    /// Read a slot by its **byte** offset, the way a disassembly listing names it.
    #[inline]
    pub fn at(&self, byte_offset: usize) -> i32 {{
        self.raw[byte_offset / 4]
    }}
}}

/// How a field's value string is turned into the stored integer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Parser {{
    /// `0x0057FA60` \u2192 `RString::ToInt` \u2192 `_wtoi`. Scale 1.
    Wtoi,
    /// `0x0057F950` \u2192 `RString::AsScaled(scale)` at `0x00A1D110`.
    Scaled(i32),
    /// The loader site uses neither helper and was not classified. Two fields
    /// (`unit_block_radius`, `americans_marine_entrench`); guessing would be folklore.
    Unclassified,
}}

/// One named field of the block.
#[derive(Clone, Copy, Debug)]
pub struct RuleField {{
    /// Lowercase name as the loader binds it (the XML tag is the uppercase form).
    pub name: &'static str,
    /// Byte offset from the `RULES` singleton.
    pub offset: u16,
    /// Slots: 1 for scalars, N for the 31 array fields.
    pub count: u16,
    pub parser: Parser,
    /// VA of the binder site the name was recovered from.
    pub binder_ea: u32,
}}

/// One recovered slot with the text it was parsed from and the integer the engine stores.
///
/// This is the tokenizer's test corpus: `scale` is the field's, never the string's.
#[derive(Clone, Copy, Debug)]
pub struct RuleSlot {{
    pub name: &'static str,
    /// Array index; 0 for scalars.
    pub index: u16,
    pub offset: u16,
    /// 1 for `_wtoi` fields, else 100 / 192 / 256.
    pub scale: i32,
    /// The `value=` / `entryN=` text from the shipped `rules.xml`.
    pub xml_value: &'static str,
    /// What the engine stores after parsing `xml_value` at `scale`.
    pub stored: i32,
}}

''')

    out(f"/// Every named field, ordered by offset. {len(fields)} entries. `static`, not `const`:\n/// it is only ever iterated, and a const would be copied at each use site.\n")
    out(f"pub static FIELDS: [RuleField; {len(fields)}] = [\n")
    for r in fields:
        if r["parser"] == "scaled":
            p = f'Parser::Scaled({r["scale"]})'
        elif r["parser"] == "wtoi":
            p = "Parser::Wtoi"
        else:
            p = "Parser::Unclassified"
        out(
            f'    RuleField {{ name: "{r["name"]}", offset: {r["offset"]}, '
            f'count: {r["count"]}, parser: {p}, binder_ea: 0x{r["binder_ea"]} }},\n'
        )
    out("];\n\n")

    out(
        f"/// Every slot whose parse mode and stored value are both recovered: {len(slots)} of\n"
        f"/// {sum(r['count'] for r in fields)}. The tokenizer must reproduce every one.\n"
    )
    out(f"pub static SLOTS: [RuleSlot; {len(slots)}] = [\n")
    for name, idx, off, scale, text, stored in slots:
        out(
            f'    RuleSlot {{ name: "{name}", index: {idx}, offset: {off}, scale: {scale}, '
            f'xml_value: "{esc(text)}", stored: {stored} }},\n'
        )
    out("];\n\n")

    out(
        "/// The block as shipped. Slots listed in [`UNRECOVERED`] hold `0` as a placeholder\n"
        "/// and are **not** measurements.\n"
    )
    out(f"pub const SHIPPED: [i32; RULES_DWORDS] = [\n")
    line = "    "
    for i, v in enumerate(shipped):
        tok = f"{v if v is not None else 0}, "
        if len(line) + len(tok) > 96:
            out(line.rstrip() + "\n")
            line = "    "
        line += tok
    out(line.rstrip() + "\n];\n\n")

    out(
        f"/// Dword indices where [`SHIPPED`] is a placeholder: {len(unrecovered)} slots whose loader\n"
        "/// call site or shipped value was not recovered. Reading one is reading a `0` we made up.\n"
    )
    out("pub const UNRECOVERED: [usize; %d] = [%s];\n\n" % (len(unrecovered), ", ".join(str(i) for i in unrecovered)))

    # ---- accessors -------------------------------------------------------------------
    out("impl Rules {\n")
    for r in fields:
        name = r["name"]
        ident = f"r#{name}" if name in RUST_KW else name
        off = r["offset"]
        if r["parser"] == "scaled":
            pdoc = f"`AsScaled({r['scale']})`"
        elif r["parser"] == "wtoi":
            pdoc = "`_wtoi`"
        else:
            pdoc = "**parse mode unclassified**"
        e0 = r["entries"][0]
        if r["count"] == 1:
            shipped_doc = (
                f'`"{short(e0["xml_value"])}"` \u2192 `{e0["stored"]}`'
                if e0["xml_value"] is not None and e0["stored"] is not None
                else "not recovered"
            )
            out(
                f"    /// `{name.upper()}` \u2014 offset {off}, {pdoc}. Shipped: {shipped_doc}.\n"
                f"    #[inline]\n"
                f"    pub fn {ident}(&self) -> i32 {{ self.raw[{off // 4}] }}\n"
            )
        else:
            vals = ", ".join(
                str(e["stored"]) if e["stored"] is not None else "?" for e in r["entries"]
            )
            out(
                f"    /// `{name.upper()}[{r['count']}]` \u2014 offset {off}, {pdoc}. Shipped: [{vals}].\n"
                f"    ///\n"
                f"    /// # Panics\n"
                f"    /// Out of range. The engine reads past the end of a rules array without\n"
                f"    /// checking; we would rather stop than read the next field.\n"
                f"    #[inline]\n"
                f"    pub fn {ident}(&self, i: usize) -> i32 {{\n"
                f"        assert!(i < {r['count']}, \"{name} has {r['count']} entries\");\n"
                f"        self.raw[{off // 4} + i]\n"
                f"    }}\n"
            )
    out("}\n")


if __name__ == "__main__":
    main()
