//! Shipped-rules loader: `buildingrules.xml`, `unitrules.xml`, `techrules.xml`,
//! `rules.xml`, `citytemplates.xml`.
//!
//! These are **shipped game data files**, which `README-LLM.md` admits as ground
//! truth. Nothing here is folklore and nothing is hand-typed: every number the
//! game model uses is read out of `ron-data/` at load time, and the loader
//! refuses rather than guesses when a field is missing.
//!
//! # Why a hand-rolled scanner
//!
//! `don-ai` has no third-party dependencies and this lane is not going to add
//! one for five element shapes. The shipped XML is machine-generated by XMLSpy
//! and is strictly `<TAG>text</TAG>` or `<TAG attr="…"/>` inside one repeated
//! record element per file, so a tag scanner is sufficient and is easier to
//! audit than a parser combinator.
//!
//! # Cost encoding [measured, `ron-data/buildingrules.xml` line 45]
//!
//! `<!--COST = Resource cost to construct this building (multiply by 10)-->`,
//! and `rules.xml` carries `UNIT_COST_FACTOR`, `BUILD_COST_FACTOR` and
//! `TECH_COST_FACTOR`, all `10 resources`. The text form is
//! `N<letter>[/N<letter>…]` where the letters are the `ABBREV` column of
//! `resourcerules.xml`, lowercased:
//!
//! | letter | `RESOURCE` | slot |
//! |---|---|---|
//! | `f` | Food      | 0 |
//! | `t` | Timber    | 1 |
//! | `g` | Wealth    | 2 |
//! | `k` | Knowledge | 3 |
//! | `m` | Metal     | 4 |
//! | `o` | Oil       | 5 |
//!
//! Slots 0..=3 agree with `don_sim::mechanics::RES_*`, which pins them from the
//! binary. Slots 4 and 5 are **not** pinned by code there; the ordering above is
//! the order of `<RESOURCE>` records in `resourcerules.xml` and the order of
//! `CITY_GATHER`'s `entry0..entry5` attributes (`10food`, `10timb`, `0gd`,
//! `0know`, `0met`, `0oil`), which is shipped data, not a wiki.
//! `TypeData::costs` is `int[6]` at `+0x18` (`schema/types.json`), so six slots
//! is also what the engine stores.

use std::collections::HashMap;
use std::path::Path;

/// Number of resource slots — `TypeData::costs` is `int[6]` at `+0x18`.
pub const NRES: usize = 6;

/// Resource slot names in shipped order (see the module docs).
pub const RES_NAMES: [&str; NRES] = ["Food", "Timber", "Wealth", "Knowledge", "Metal", "Oil"];

/// One `<BUILDING>`, `<UNIT>` or `<TECH>` record, reduced to the fields the
/// production AI and the economy need.
#[derive(Clone, Debug, Default)]
pub struct TypeRules {
    pub name: String,
    /// `TypeData::costs`, already multiplied by the `*_COST_FACTOR`.
    pub costs: [i32; NRES],
    /// `TypeData::job_time`, in frames (`JOB_TIME = How long for one citizen to
    /// build, in 1/15sec`).
    pub job_time: i32,
    /// `PREQ0..PREQ2`, with `none` dropped.
    pub preq: Vec<String>,
    /// `FROM` — the predecessor this type upgrades from, if any.
    pub from: Option<String>,
    /// `WHERE` — the building this unit/tech is produced at.
    pub where_: Option<String>,
    /// `BUILD_FLAGS` (buildings) or `FLAGS` (units), verbatim.
    pub flags: String,
    /// `POP` (units only).
    pub pop: i32,
    /// `AGE` (techs only).
    pub age: i32,
    /// `<SUPPORT>` upkeep, parsed like a cost. Units only.
    pub support: [i32; NRES],
}

impl TypeRules {
    /// True when the building carries the `g` build flag — *"Building is a
    /// resource gatherer"*, which is `BuildTypeData::build_flags & 0x40`
    /// (`+0x2C0`), the bit `max_workers_at_building` `0x009F2520` tests before
    /// it will report a worker capacity at all.
    pub fn is_gatherer(&self) -> bool {
        self.flags.contains('g')
    }
}

/// The `rules.xml` scalars this crate reads. Each carries the element it came
/// from so a divergence is one grep away.
#[derive(Clone, Debug)]
pub struct Constants {
    /// `<GATHER_RATE value="450 frames"/>`. Also `Constants +0x27C`.
    pub gather_rate: i32,
    /// `<PEASANT_RATE value="10 resources"/>`.
    pub peasant_rate: i32,
    /// `<CITY_GATHER entry0="10food" … entry5="0oil"/>`.
    pub city_gather: [i32; NRES],
    /// `<STARTING_GOODS entry0="200food" … entry5="100oil"/>`.
    pub starting_goods: [i32; NRES],
    /// `<POP_CAP entry0="25" … entry7="200 pop cap"/>`, indexed by age.
    pub pop_cap: [i32; 8],
    /// `<COMMERCE_CAP entry0="70" … entry7="500 commerce cap"/>`, by age.
    pub commerce_cap: [i32; 8],
    pub unit_cost_factor: i32,
    pub build_cost_factor: i32,
    pub tech_cost_factor: i32,
}

/// Everything loaded from `ron-data/`.
#[derive(Clone, Debug)]
pub struct Rules {
    pub buildings: HashMap<String, TypeRules>,
    pub units: HashMap<String, TypeRules>,
    pub techs: HashMap<String, TypeRules>,
    pub constants: Constants,
    /// `citytemplates.xml`: the buildings a starting town is seeded with. All 17
    /// shipped templates are `size="small"` and every one of them is 3 Farms +
    /// 1 Library, so this is the multiset of the first template, not a guess.
    pub small_town_template: Vec<String>,
    /// Technology names in file order, which is the order `techrules.xml`
    /// declares them and therefore the order the age techs appear in.
    pub tech_order: Vec<String>,
}

/// Map a lowercase resource abbreviation to its slot. See the module docs.
fn res_slot(abbrev: &str) -> Option<usize> {
    match abbrev {
        "f" => Some(0),
        "t" => Some(1),
        "g" => Some(2),
        "k" => Some(3),
        "m" => Some(4),
        "o" => Some(5),
        _ => None,
    }
}

/// Parse a `COST`/`SUPPORT` string such as `"5t/5f"`, `"10t/5m"`, `"1f support"`
/// or `""` into a six-slot vector, scaled by `factor`.
///
/// Unknown suffixes are ignored rather than guessed at; `"none"` and the empty
/// string yield an all-zero cost, which is what the engine's `int[6]` starts as.
pub fn parse_cost(text: &str, factor: i32) -> [i32; NRES] {
    let mut out = [0i32; NRES];
    for term in text.split('/') {
        let t = term.trim();
        let digits: String = t.chars().take_while(|c| c.is_ascii_digit()).collect();
        if digits.is_empty() {
            continue;
        }
        let letters: String = t[digits.len()..]
            .chars()
            .take_while(|c| c.is_ascii_alphabetic())
            .collect::<String>()
            .to_ascii_lowercase();
        let n: i32 = digits.parse().unwrap_or(0);
        // `1f support` — the resource letter is the first token only.
        if let Some(slot) =
            res_slot(&letters).or_else(|| res_slot(&letters[..1.min(letters.len())]))
        {
            out[slot] = out[slot].saturating_add(n.saturating_mul(factor));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// A minimal tag scanner
// ---------------------------------------------------------------------------

/// Split `xml` into the text of every `<record>…</record>` block.
fn records<'a>(xml: &'a str, record: &str) -> Vec<&'a str> {
    let open = format!("<{record}>");
    let close = format!("</{record}>");
    let mut out = Vec::new();
    let mut i = 0;
    while let Some(s) = xml[i..].find(&open) {
        let start = i + s + open.len();
        match xml[start..].find(&close) {
            Some(e) => {
                out.push(&xml[start..start + e]);
                i = start + e + close.len();
            }
            None => break,
        }
    }
    out
}

/// The text of the first `<tag>…</tag>` in `block`, trimmed. Also matches the
/// self-closing `<tag/>` form, which the shipped files use for empty fields.
fn tag(block: &str, name: &str) -> Option<String> {
    let open = format!("<{name}>");
    if let Some(s) = block.find(&open) {
        let start = s + open.len();
        let close = format!("</{name}>");
        if let Some(e) = block[start..].find(&close) {
            return Some(block[start..start + e].trim().to_string());
        }
    }
    if block.contains(&format!("<{name}/>")) {
        return Some(String::new());
    }
    None
}

/// The value of `attr` on the first `<elem …/>` in `xml`.
fn attr_of(xml: &str, elem: &str, attr: &str) -> Option<String> {
    let open = format!("<{elem} ");
    let s = xml.find(&open)?;
    let end = xml[s..].find("/>")? + s;
    let seg = &xml[s..end];
    let key = format!("{attr}=\"");
    let a = seg.find(&key)? + key.len();
    let b = seg[a..].find('"')? + a;
    Some(seg[a..b].to_string())
}

/// `<ELEM value="450 frames"/>` → 450.
fn rule_int(xml: &str, elem: &str) -> Option<i32> {
    let v = attr_of(xml, elem, "value")?;
    let digits: String = v
        .trim()
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

/// `<ELEM entry0="10food" entry1="10timb" …/>` → the leading integers.
fn rule_entries<const N: usize>(xml: &str, elem: &str) -> Option<[i32; N]> {
    let mut out = [0i32; N];
    for (i, slot) in out.iter_mut().enumerate() {
        let v = attr_of(xml, elem, &format!("entry{i}"))?;
        let digits: String = v
            .trim()
            .chars()
            .take_while(|c| c.is_ascii_digit())
            .collect();
        *slot = digits.parse().ok()?;
    }
    Some(out)
}

/// The shipped files spell "no value" three ways: `none`, `None` and `disable`.
/// `techrules.xml` uses the capitalised form 83 times, including on every tech
/// `economic.bhs` researches first, so a case-sensitive test silently turns
/// `Written Word` into a tech that needs a tech called "None" and the whole
/// opening deadlocks. It did, for one run; hence this function.
fn is_sentinel(v: &str) -> bool {
    v.is_empty() || v.eq_ignore_ascii_case("none") || v.eq_ignore_ascii_case("disable")
}

fn preqs(block: &str) -> Vec<String> {
    ["PREQ0", "PREQ1", "PREQ2"]
        .iter()
        .filter_map(|t| tag(block, t))
        .filter(|p| !is_sentinel(p))
        .collect()
}

fn opt_name(block: &str, t: &str) -> Option<String> {
    tag(block, t).filter(|v| !is_sentinel(v))
}

impl Rules {
    /// Load every rules file from a `ron-data` directory.
    ///
    /// # Errors
    /// Any missing or unreadable file, or a `rules.xml` that lacks one of the
    /// scalars in [`Constants`]. It never falls back to a built-in number — a
    /// silent default is exactly how folklore gets in.
    pub fn load(dir: &Path) -> Result<Rules, String> {
        let read = |n: &str| -> Result<String, String> {
            std::fs::read_to_string(dir.join(n)).map_err(|e| format!("{n}: {e}"))
        };
        let rules_xml = read("rules.xml")?;

        let need_i = |e: &str| -> Result<i32, String> {
            rule_int(&rules_xml, e).ok_or_else(|| format!("rules.xml: missing <{e} value=…/>"))
        };
        let constants = Constants {
            gather_rate: need_i("GATHER_RATE")?,
            peasant_rate: need_i("PEASANT_RATE")?,
            city_gather: rule_entries::<NRES>(&rules_xml, "CITY_GATHER")
                .ok_or("rules.xml: missing CITY_GATHER")?,
            starting_goods: rule_entries::<NRES>(&rules_xml, "STARTING_GOODS")
                .ok_or("rules.xml: missing STARTING_GOODS")?,
            pop_cap: rule_entries::<8>(&rules_xml, "POP_CAP")
                .ok_or("rules.xml: missing POP_CAP")?,
            commerce_cap: rule_entries::<8>(&rules_xml, "COMMERCE_CAP")
                .ok_or("rules.xml: missing COMMERCE_CAP")?,
            unit_cost_factor: need_i("UNIT_COST_FACTOR")?,
            build_cost_factor: need_i("BUILD_COST_FACTOR")?,
            tech_cost_factor: need_i("TECH_COST_FACTOR")?,
        };

        let bxml = read("buildingrules.xml")?;
        let mut buildings = HashMap::new();
        for b in records(&bxml, "BUILDING") {
            let name = match tag(b, "NAME") {
                Some(n) if !n.is_empty() => n,
                _ => continue,
            };
            buildings.insert(
                name.clone(),
                TypeRules {
                    name,
                    costs: parse_cost(
                        &tag(b, "COST").unwrap_or_default(),
                        constants.build_cost_factor,
                    ),
                    job_time: tag(b, "JOB_TIME").and_then(|v| v.parse().ok()).unwrap_or(0),
                    preq: preqs(b),
                    from: opt_name(b, "FROM"),
                    where_: None,
                    flags: tag(b, "BUILD_FLAGS").unwrap_or_default(),
                    pop: 0,
                    age: 0,
                    support: [0; NRES],
                },
            );
        }

        let uxml = read("unitrules.xml")?;
        let mut units = HashMap::new();
        for u in records(&uxml, "UNIT") {
            let name = match tag(u, "NAME") {
                Some(n) if !n.is_empty() => n,
                _ => continue,
            };
            units.insert(
                name.clone(),
                TypeRules {
                    name,
                    costs: parse_cost(
                        &tag(u, "COST").unwrap_or_default(),
                        constants.unit_cost_factor,
                    ),
                    job_time: tag(u, "JOB_TIME").and_then(|v| v.parse().ok()).unwrap_or(0),
                    preq: preqs(u),
                    from: opt_name(u, "FROM"),
                    where_: opt_name(u, "WHERE"),
                    flags: tag(u, "FLAGS").unwrap_or_default(),
                    pop: tag(u, "POP").and_then(|v| v.parse().ok()).unwrap_or(0),
                    age: 0,
                    // SUPPORT is per-unit upkeep and is *not* multiplied by a
                    // cost factor (`BUILD_SUPPORT_FACTOR` is `1 resources`).
                    support: parse_cost(&tag(u, "SUPPORT").unwrap_or_default(), 1),
                },
            );
        }

        let txml = read("techrules.xml")?;
        let mut techs = HashMap::new();
        let mut tech_order = Vec::new();
        for t in records(&txml, "TECH") {
            let name = match tag(t, "NAME") {
                Some(n) if !n.is_empty() => n,
                _ => continue,
            };
            tech_order.push(name.clone());
            techs.insert(
                name.clone(),
                TypeRules {
                    name,
                    costs: parse_cost(
                        &tag(t, "COST").unwrap_or_default(),
                        constants.tech_cost_factor,
                    ),
                    job_time: tag(t, "JOB_TIME").and_then(|v| v.parse().ok()).unwrap_or(0),
                    preq: preqs(t),
                    from: None,
                    where_: opt_name(t, "WHERE"),
                    flags: String::new(),
                    pop: 0,
                    age: tag(t, "AGE").and_then(|v| v.parse().ok()).unwrap_or(0),
                    support: [0; NRES],
                },
            );
        }

        let cxml = read("citytemplates.xml")?;
        let mut small_town_template = Vec::new();
        if let Some(first) = cxml.find("<TEMPLATE size=\"small\">") {
            let seg = &cxml[first..];
            let end = seg.find("</TEMPLATE>").unwrap_or(seg.len());
            let mut rest = &seg[..end];
            while let Some(p) = rest.find("<Build ") {
                let s = &rest[p..];
                let e = s.find("/>").map(|e| e + 2).unwrap_or(s.len());
                if let Some(t) = attr_of(&s[..e], "Build", "type") {
                    small_town_template.push(t);
                }
                rest = &rest[p + e..];
            }
        }

        if buildings.is_empty() || units.is_empty() || techs.is_empty() {
            return Err("rules files parsed but produced no records".into());
        }
        Ok(Rules {
            buildings,
            units,
            techs,
            constants,
            small_town_template,
            tech_order,
        })
    }

    /// Cost of any named type, whichever table it lives in.
    pub fn cost_of(&self, name: &str) -> Option<[i32; NRES]> {
        self.buildings
            .get(name)
            .or_else(|| self.units.get(name))
            .or_else(|| self.techs.get(name))
            .map(|t| t.costs)
    }

    /// `job_time` of any named type, in frames.
    pub fn job_time_of(&self, name: &str) -> Option<i32> {
        self.buildings
            .get(name)
            .or_else(|| self.units.get(name))
            .or_else(|| self.techs.get(name))
            .map(|t| t.job_time)
    }
}

/// The default `ron-data` directory relative to the repo root, used by the
/// binaries and the tests. Absent in a checkout without game data, in which case
/// callers skip rather than fabricate.
pub fn default_data_dir() -> std::path::PathBuf {
    // `CARGO_MANIFEST_DIR` is `<repo>/crates/don-ai`.
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../ron-data")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cost_strings_parse_to_the_engine_six_slot_vector() {
        // `Large City` ships `<COST>2t/2f</COST>`, factor 10.
        assert_eq!(parse_cost("2t/2f", 10), [20, 20, 0, 0, 0, 0]);
        // `<COST>10t/5m</COST>`.
        assert_eq!(parse_cost("10t/5m", 10), [0, 100, 0, 0, 50, 0]);
        // Techs use knowledge and food: `<COST>25k/25f</COST>`.
        assert_eq!(parse_cost("25k/25f", 10), [250, 0, 0, 250, 0, 0]);
        // Upkeep strings carry a trailing word.
        assert_eq!(parse_cost("1f support", 1), [1, 0, 0, 0, 0, 0]);
        assert_eq!(parse_cost("", 10), [0; NRES]);
        assert_eq!(parse_cost("none", 10), [0; NRES]);
    }

    fn rules() -> Option<Rules> {
        Rules::load(&default_data_dir()).ok()
    }

    #[test]
    fn shipped_rules_load_and_agree_with_the_binary_derived_constants() {
        let Some(r) = rules() else { return }; // ron-data is gitignored
                                               // `EconomyRules::shipped()` in don-sim carries these out of the binary's
                                               // own `Constants`; the XML must agree or one of them is wrong.
        assert_eq!(r.constants.gather_rate, 450);
        assert_eq!(
            r.constants.commerce_cap,
            [70, 100, 150, 200, 260, 320, 400, 500]
        );
        assert_eq!(r.constants.city_gather, [10, 10, 0, 0, 0, 0]);
        assert_eq!(r.constants.starting_goods, [200, 200, 100, 100, 100, 100]);
        assert_eq!(r.constants.peasant_rate, 10);
        assert_eq!(
            (r.constants.build_cost_factor, r.constants.unit_cost_factor),
            (10, 10)
        );
    }

    #[test]
    fn the_types_the_economic_opening_names_all_exist() {
        let Some(r) = rules() else { return };
        for b in [
            "Small City",
            "Large City",
            "Farm",
            "Woodcutter's Camp",
            "Mine",
            "Dock",
            "Library",
            "Market",
            "Temple",
            "Barracks",
            "Lumber Mill",
            "Granary",
            "Smelter",
            "University",
        ] {
            assert!(r.buildings.contains_key(b), "missing building {b}");
        }
        // Note the shipped plural: the unit type really is `Fishermen`, while
        // the citizen type is singular. That inconsistency is why the script's
        // `"Citizens"` typo is plausible enough to have survived shipping.
        for u in ["Citizen", "Scholar", "Merchant", "Caravan", "Fishermen"] {
            assert!(r.units.contains_key(u), "missing unit {u}");
        }
        for t in [
            "City State",
            "The Art of War",
            "Written Word",
            "Classical Age",
        ] {
            assert!(r.techs.contains_key(t), "missing tech {t}");
        }
        // The shipped bug this lane reported: `Citizens` is not a type.
        assert!(!r.units.contains_key("Citizens"));
    }

    #[test]
    fn the_starting_town_is_three_farms_and_a_library() {
        let Some(r) = rules() else { return };
        let mut t = r.small_town_template.clone();
        t.sort();
        assert_eq!(t, vec!["Farm", "Farm", "Farm", "Library"]);
    }

    #[test]
    fn gatherer_buildings_carry_the_g_flag() {
        let Some(r) = rules() else { return };
        for b in ["Farm", "Woodcutter's Camp", "Mine"] {
            assert!(r.buildings[b].is_gatherer(), "{b} should have build flag g");
        }
        assert!(!r.buildings["Library"].is_gatherer());
    }
}
