//! Tables captured out of `riseofnations.exe`.
//!
//! GENERATED by `crates/don-content/gen/gen_tables.py`. Do not edit by hand.
//!
//! Every constant below is **[measured]** — read from the shipped image at a VA
//! resolved through `ron-bin/sbl/rise.pdb`, or from the PDB's own type stream.
//! The generator asserts the two self-describing tables index themselves
//! (`ModCategoryInfo[i].category == i`, `SteamWorkshopTagNames[i].tag == i`), so a
//! stride or base-address error cannot pass silently.

#![allow(dead_code)]

use crate::vfs::{ModCategory, TagLink, WorkshopTag};

/// `s_ModCategoryInfo` `0x00C07AD0`, 12 x 120 bytes.
///
/// `relative_dir` is the engine's `relativeDirectory` with `\\` rewritten to `/`;
/// resolution is case-insensitive either way. `CAT_ROOT`'s is empty, which is why
/// it matches every path and must stay last in the classify scan.
pub struct CategoryInfo {
    pub name: &'static str,
    pub relative_dir: &'static str,
    pub recursive: bool,
}

pub static CATEGORY_INFO: [CategoryInfo; 12] = [
    CategoryInfo {
        name: "AI",
        relative_dir: "ai/scripts/",
        recursive: false,
    },
    CategoryInfo {
        name: "ART",
        relative_dir: "art/",
        recursive: true,
    },
    CategoryInfo {
        name: "CONQUEST",
        relative_dir: "conquest/",
        recursive: true,
    },
    CategoryInfo {
        name: "DATA",
        relative_dir: "data/",
        recursive: false,
    },
    CategoryInfo {
        name: "MAPSTYLES",
        relative_dir: "mapstyles/",
        recursive: false,
    },
    CategoryInfo {
        name: "SCENARIO",
        relative_dir: "scenario/",
        recursive: true,
    },
    CategoryInfo {
        name: "SOUNDS",
        relative_dir: "sounds/",
        recursive: true,
    },
    CategoryInfo {
        name: "TERRAIN",
        relative_dir: "terrain art/",
        recursive: true,
    },
    CategoryInfo {
        name: "TRIBES",
        relative_dir: "tribes/",
        recursive: false,
    },
    CategoryInfo {
        name: "REPLAYS",
        relative_dir: "replays/",
        recursive: false,
    },
    CategoryInfo {
        name: "SAVES",
        relative_dir: "saves/",
        recursive: false,
    },
    CategoryInfo {
        name: "ROOT",
        relative_dir: "",
        recursive: false,
    },
];

/// `s_SteamWorkshopTagNames` `0x00C06678`, 13 x 44 bytes.
pub static TAG_NAMES: [&str; 13] = [
    "AI",
    "Art",
    "Conquest",
    "Cursors",
    "Data",
    "Mods",
    "MapStyles",
    "Replays",
    "Scenarios",
    "Sound",
    "Terrain",
    "Tribes",
    "Other",
];

/// `s_SteamWorkshopTagLinks` `0x00C068D0`, 64 x 72 bytes.
///
/// This is the engine's own answer to *what content is a mod made of*: a tag is
/// awarded when the mod's file list for `category` contains a file matching
/// `pattern`. It is also the closest thing retail has to a manifest schema.
pub static TAG_LINKS: [TagLink; 64] = [
    TagLink {
        tag: WorkshopTag::Ai,
        category: ModCategory::Ai,
        pattern: ".bho",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Ai,
        category: ModCategory::Ai,
        pattern: ".bhs",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Art,
        category: ModCategory::Art,
        pattern: ".bh3",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Art,
        category: ModCategory::Art,
        pattern: ".bha",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Art,
        category: ModCategory::Art,
        pattern: ".mot",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Art,
        category: ModCategory::Art,
        pattern: ".tga",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Art,
        category: ModCategory::Art,
        pattern: ".wmv",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".png",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".bhs",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".xml",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".4",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".7",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".9",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".10",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".12",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".16",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".17",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Conquest,
        category: ModCategory::Conquest,
        pattern: ".18",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Cursors,
        category: ModCategory::Art,
        pattern: ".cur",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Root,
        pattern: ".txt",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Root,
        pattern: ".wmv",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Root,
        pattern: ".bhs",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Root,
        pattern: ".xml",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".4",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".7",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".9",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".10",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".12",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".16",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".17",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".18",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".bhs",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".dtd",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".sps",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".xml",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Data,
        category: ModCategory::Data,
        pattern: ".xsd",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Mods,
        category: ModCategory::Root,
        pattern: "info.xml",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::MapStyles,
        category: ModCategory::MapStyles,
        pattern: ".xml",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Replays,
        category: ModCategory::Replays,
        pattern: ".rcx",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".4",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".7",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".9",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".10",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".12",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".16",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".17",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".18",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".bhs",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".sce",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".scx",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".wav",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Scenarios,
        category: ModCategory::Scenario,
        pattern: ".xml",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Sounds,
        category: ModCategory::Sounds,
        pattern: ".wav",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Terrain,
        category: ModCategory::Terrain,
        pattern: ".bh3",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Terrain,
        category: ModCategory::Terrain,
        pattern: ".png",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Terrain,
        category: ModCategory::Terrain,
        pattern: ".tga",
        recursive: true,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".4",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".7",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".9",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".10",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".12",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".16",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".17",
        recursive: false,
    },
    TagLink {
        tag: WorkshopTag::Tribe,
        category: ModCategory::Tribes,
        pattern: ".18",
        recursive: false,
    },
];

/// `ModManager::isMapForbidden` `0x00A21140` — the 21 map-style files a mod is not
/// permitted to override, extracted from the function's own pushed `.rdata` literals.
///
/// This is the **only** content-replacement veto in the engine: `calcFilePath`
/// consults it for `CAT_MAPSTYLES` and for no other category.
pub static FORBIDDEN_MAPSTYLES: [&str; 21] = [
    "africa.xml",
    "amazon.xml",
    "britishisles.xml",
    "colonialpowers.xml",
    "conquestmap.xml",
    "conquestmapsea.xml",
    "default.xml",
    "eastindies.xml",
    "eastwest.xml",
    "editormap.xml",
    "greatlakes_trial.xml",
    "himalayas.xml",
    "mediterranean.xml",
    "newworld.xml",
    "niledelta.xml",
    "oldworld.xml",
    "outback.xml",
    "sahara.xml",
    "seapower.xml",
    "soutwestmesa.xml",
    "warringstates.xml",
];

/// `enum TypeIndex` (PDB type stream) — the closed, compile-time type-id space.
///
/// A retail mod cannot add an entry here: ids are an enum baked into the image and
/// `Balance::final_balance_table` `0x00C12BF4` is a static `short[493][493]`.
pub const RETAIL_NUM_TYPES: u16 = 806;
/// Side length of the static combat matrix. Note it is **smaller** than
/// `RETAIL_NUM_TYPES`: the matrix only spans ids `0..493`.
pub const BALANCE_TABLE_SIDE: u16 = 493;

/// `[base, end)` per type family, from `BASE_*`/`END_*` in `enum TypeIndex`.
pub static TYPE_RANGES: [(&str, u16, u16); 8] = [
    ("Good", 0, 50),
    ("Unit", 50, 402),
    ("Gaia", 402, 414),
    ("Build", 414, 543),
    ("Item", 543, 544),
    ("Tech", 544, 629),
    ("Spell", 629, 684),
    ("Bonus", 684, 806),
];
