// Generate the command-wire codec from `schema/command-wire.json`, for both sides.
//
//     node web/tools/gen-wire.mjs
//       -> web/public/js/wire.gen.js     (browser encoder)
//       -> web/wasm/src/wire_gen.rs      (wasm decoder)
//
// # Why generated
//
// `schema/command-wire.json` is the derived artefact: 82 opcodes with struct name, wire
// size and every field's byte offset and type, recovered from `rise.pdb` and cross-checked
// against `CommandPackage::process` (`FUN_0094a700`). Transcribing a field offset by hand
// is how a copy silently drifts from the derivation. So neither side of this app contains a
// hand-written offset — both are emitted from that file, and a change to it changes both.
//
// # Field widths are inferred, and the inference is exact for these structs
//
// The JSON gives each field's offset and type name but not its width. Every command struct
// is `packed` (the PDB says so) and every field is listed in offset order, so a field's
// width is the next field's offset minus its own, and the last field's width is the wire
// size minus its offset. That reconstructs the width of `QueuePos`, `OrderIndex`, `Coord`
// and the other opaque typedefs without guessing at them.
//
// # The one variable-length command
//
// `GroupCommand` (0x00) is selection, and it is the only command here whose length depends
// on its contents: `num` u8, `who` i8, then `num` entries. The entry type is
// `GroupCommand::<unnamed-type-list>`, which `llvm-pdbutil dump --types rise.pdb` shows to
// be `struct { short o; }`, sizeof 2 — so an entry is a 2-byte object index, and the
// declared wire size 5 is the one-entry case (1 + 1 + 1 + 2). That is emitted as a
// hand-written special case in both outputs, marked as such.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const SRC = join(REPO, 'schema', 'command-wire.json');

const cmds = JSON.parse(readFileSync(SRC, 'utf8'));

/** Signed-ness by declared type name. Unknown typedefs default to signed. */
const UNSIGNED = new Set(['unsigned char', 'unsigned short', 'unsigned long', 'unsigned int']);
const FLOATY = new Set(['float']);

function widths(c) {
  const fs = [...c.fields].sort((a, b) => a.off - b.off);
  return fs.map((f, i) => {
    const end = i + 1 < fs.length ? fs[i + 1].off : c.size;
    return { ...f, bytes: end - f.off, unsigned: UNSIGNED.has(f.type), float: FLOATY.has(f.type) };
  });
}

const table = cmds.map((c) => ({
  op: c.op, struct: c.struct, size: c.size, method: c.method, fields: widths(c),
}));

// ---------------------------------------------------------------------------------------
// JS
// ---------------------------------------------------------------------------------------

const jsHeader = `// GENERATED by web/tools/gen-wire.mjs from schema/command-wire.json. Do not edit.
//
// The engine's command wire format: ${table.length} opcodes, every field offset taken from the
// derivation rather than typed in here. \`encode\` writes the exact bytes the engine's own
// \`CommandPackage::process\` dispatch expects for that opcode; fields left out of the value
// object are written as zero.
//
// Widths are reconstructed from consecutive field offsets and the struct's wire size — see
// the generator for why that is exact for these packed structs.
`;

function jsFieldLiteral(f) {
  return `{ name: ${JSON.stringify(f.name)}, off: ${f.off}, bytes: ${f.bytes}, ` +
    `type: ${JSON.stringify(f.type)}, unsigned: ${f.unsigned}, float: ${f.float} }`;
}

const js = `${jsHeader}
export const COMMANDS = {
${table.map((c) => `  0x${c.op.toString(16).padStart(2, '0')}: { op: ${c.op}, struct: ${JSON.stringify(c.struct)}, size: ${c.size}, method: ${JSON.stringify(c.method)},
    fields: [${c.fields.length ? '\n      ' + c.fields.map(jsFieldLiteral).join(',\n      ') + ',\n    ' : ''}] }`).join(',\n')},
};

/** opcode -> struct name, for logging and for the UI. */
export const OP = {
${table.map((c) => `  ${c.struct.replace(/Command$/, '').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()}: 0x${c.op.toString(16).padStart(2, '0')}`).join(',\n')},
};

function put(dv, off, bytes, unsigned, float, v) {
  if (float) { dv.setFloat32(off, v, true); return; }
  switch (bytes) {
    case 1: unsigned ? dv.setUint8(off, v & 0xff) : dv.setInt8(off, (v << 24) >> 24); return;
    case 2: unsigned ? dv.setUint16(off, v & 0xffff, true) : dv.setInt16(off, (v << 16) >> 16, true); return;
    case 4: unsigned ? dv.setUint32(off, v >>> 0, true) : dv.setInt32(off, v | 0, true); return;
    default: {
      // Opaque wide fields (wchar_t[N], vertex arrays) are written as a zero-filled span;
      // this app never sends one and pretending otherwise would be worse than refusing.
      for (let i = 0; i < bytes; i++) dv.setUint8(off + i, 0);
    }
  }
}

/**
 * Encode one command into its exact wire bytes.
 *
 * Byte 0 is the opcode, as the engine's dispatch reads it; the rest is the struct's own
 * layout. Returns a \`Uint8Array\` of exactly \`COMMANDS[op].size\` bytes.
 */
export function encode(op, values = {}) {
  const c = COMMANDS[op];
  if (!c) throw new Error('unknown opcode 0x' + op.toString(16));
  if (op === 0x00) throw new Error('GroupCommand is variable length: use encodeGroup');
  const buf = new Uint8Array(c.size);
  const dv = new DataView(buf.buffer);
  dv.setUint8(0, op);
  for (const f of c.fields) {
    const v = values[f.name];
    if (v === undefined) continue;
    put(dv, f.off, f.bytes, f.unsigned, f.float, v);
  }
  return buf;
}

/**
 * \`GroupCommand\` (0x00) — the engine's *selection* packet, and the only variable-length
 * command in this codec: 1 byte opcode, \`num\` u8, \`who\` i8, then \`num\` 2-byte object
 * indices. Selection being its own command is a fact about the action space, not a UI
 * convenience: the engine's orders apply to the current group.
 */
export function encodeGroup(who, ids) {
  const n = Math.min(ids.length, 255);
  const buf = new Uint8Array(3 + n * 2);
  const dv = new DataView(buf.buffer);
  dv.setUint8(0, 0x00);
  dv.setUint8(1, n);
  dv.setInt8(2, who);
  for (let i = 0; i < n; i++) dv.setInt16(3 + i * 2, ids[i], true);
  return buf;
}

/** Decode into a plain object; the inverse of \`encode\`, used by tests and the log. */
export function decode(bytes) {
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const op = dv.getUint8(0);
  const c = COMMANDS[op];
  if (!c) return { op, unknown: true };
  if (op === 0x00) {
    const n = dv.getUint8(1), who = dv.getInt8(2), list = [];
    for (let i = 0; i < n && 3 + i * 2 + 2 <= bytes.length; i++) list.push(dv.getInt16(3 + i * 2, true));
    return { op, struct: c.struct, num: n, who, list };
  }
  const out = { op, struct: c.struct };
  for (const f of c.fields) {
    if (f.off + f.bytes > bytes.length) continue;
    if (f.float) { out[f.name] = dv.getFloat32(f.off, true); continue; }
    if (f.bytes === 1) out[f.name] = f.unsigned ? dv.getUint8(f.off) : dv.getInt8(f.off);
    else if (f.bytes === 2) out[f.name] = f.unsigned ? dv.getUint16(f.off, true) : dv.getInt16(f.off, true);
    else if (f.bytes === 4) out[f.name] = f.unsigned ? dv.getUint32(f.off, true) : dv.getInt32(f.off, true);
  }
  return out;
}
`;

// ---------------------------------------------------------------------------------------
// Rust
// ---------------------------------------------------------------------------------------

const rustNames = table.map((c) => {
  const konst = c.struct.replace(/Command$/, '').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
  return { ...c, konst };
});

const rs = `//! GENERATED by \`web/tools/gen-wire.mjs\` from \`schema/command-wire.json\`. Do not edit.
//!
//! The wasm side of the engine's command wire format. The browser encodes a command with
//! the generated JS codec, posts the raw bytes, and this module reads the fields back out
//! at the derived offsets — so the byte stream between a click and the simulation is the
//! engine's own packet layout, not an envelope invented for this app.
//!
//! Field widths are reconstructed from consecutive offsets plus the struct's wire size;
//! the generator explains why that is exact here.

/// Opcode constants, named after the struct each dispatches to.
pub mod op {
${rustNames.map((c) => `    /// \`${c.struct}\` — ${c.size} bytes, \`CommandPackage::${c.method}\`.\n    pub const ${c.konst}: u8 = 0x${c.op.toString(16).padStart(2, '0')};`).join('\n')}
}

/// Declared wire size by opcode; \`None\` where the opcode is unused.
pub const SIZE: [Option<u16>; 256] = {
    let mut t = [None; 256];
${rustNames.map((c) => `    t[0x${c.op.toString(16).padStart(2, '0')}] = Some(${c.size});`).join('\n')}
    t
};

/// Struct name by opcode, for diagnostics.
pub fn struct_name(op: u8) -> &'static str {
    match op {
${rustNames.map((c) => `        0x${c.op.toString(16).padStart(2, '0')} => "${c.struct}",`).join('\n')}
        _ => "?",
    }
}

// ---- field readers, one per field this app actually consumes ---------------------------
//
// Only the fields the simulation can honour are given readers. A reader for a field
// nothing implements would be a claim that it is modelled.

#[inline]
fn i32_at(b: &[u8], off: usize) -> i32 {
    if off + 4 > b.len() { return 0; }
    i32::from_le_bytes([b[off], b[off + 1], b[off + 2], b[off + 3]])
}
#[inline]
fn i16_at(b: &[u8], off: usize) -> i16 {
    if off + 2 > b.len() { return 0; }
    i16::from_le_bytes([b[off], b[off + 1]])
}
#[inline]
fn i8_at(b: &[u8], off: usize) -> i8 {
    if off >= b.len() { return 0; } else { b[off] as i8 }
}

${(() => {
  const want = {
    0x07: ['to_x', 'to_y', 'queued', 'form'], 0x04: ['ox', 'whom', 'queued'],
    0x0a: ['to_x', 'to_y', 'queued'],
    // The four the *playable* client adds (web/wasm/src/game.rs honours each of these).
    0x13: ['ox', 'queued'],                  // GatherCommand   — send a worker to a node
    0x18: ['type', 'num'],                   // QueueUpCommand  — train/research at a producer
    0x19: ['x', 'y', 'x2', 'y2', 'type'],    // BuildCommand    — place a building
    0x30: ['who', 'o', 'type', 'uid'],       // UnqueueCommand  — cancel a queued item
  };
  const out = [];
  for (const [opStr, names] of Object.entries(want)) {
    const c = table.find((x) => x.op === Number(opStr));
    const mod = c.struct.replace(/Command$/, '').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    out.push(`/// \`${c.struct}\` (0x${c.op.toString(16).padStart(2, '0')}), ${c.size} bytes.
pub mod ${mod} {
    use super::*;
${names.map((n) => {
      const f = c.fields.find((x) => x.name === n);
      const rd = f.bytes === 4 ? 'i32_at' : f.bytes === 2 ? 'i16_at' : 'i8_at';
      const ty = f.bytes === 4 ? 'i32' : f.bytes === 2 ? 'i16' : 'i8';
      // Engine field names are C identifiers and a few collide with Rust keywords
      // (`type`, `ref`, `move`). Suffix an underscore rather than renaming, so the
      // generated name still reads as the engine's field.
      const RUST_KEYWORDS = new Set(['type', 'ref', 'move', 'box', 'match', 'fn', 'mod', 'if',
        'else', 'loop', 'where', 'use', 'as', 'in', 'let', 'self', 'super', 'crate']);
      const fname = RUST_KEYWORDS.has(f.name) ? `${f.name}_` : f.name;
      return `    /// field \`${f.name}\`: \`${f.type}\` at byte ${f.off}, ${f.bytes} byte(s).
    #[inline]
    pub fn ${fname}(b: &[u8]) -> ${ty} { ${rd}(b, ${f.off}) }`;
    }).join('\n')}
}`);
  }
  return out.join('\n\n');
})()}

/// \`GroupCommand\` (0x00) — selection. Variable length: \`num\` u8, \`who\` i8, then \`num\`
/// 2-byte object indices. Hand-written because it is the one command whose length depends
/// on its contents; the entry width comes from the PDB type record
/// \`GroupCommand::<unnamed-type-list> = struct { short o; }\`, sizeof 2.
pub mod group {
    use super::*;
    #[inline]
    pub fn num(b: &[u8]) -> usize { if b.len() > 1 { b[1] as usize } else { 0 } }
    #[inline]
    pub fn who(b: &[u8]) -> i8 { i8_at(b, 2) }
    /// Object index \`k\`, or \`None\` past the end of the packet.
    #[inline]
    pub fn entry(b: &[u8], k: usize) -> Option<i16> {
        let off = 3 + k * 2;
        if off + 2 > b.len() { None } else { Some(i16_at(b, off)) }
    }
}
`;

writeFileSync(join(REPO, 'web', 'public', 'js', 'wire.gen.js'), js);
writeFileSync(join(REPO, 'web', 'wasm', 'src', 'wire_gen.rs'), rs);
console.log(`wire.gen.js + wire_gen.rs: ${table.length} opcodes, ` +
  `${table.reduce((n, c) => n + c.fields.length, 0)} fields`);
