// @generated by crates/don-env/gen/gen_spec.py -- DO NOT EDIT BY HAND.
//
// Sources, all [measured]:
//   schema/command-wire.json  82 command opcodes, struct sizes, field layouts
//   schema/types.json         PDB TPI enums: CommandTypes, OrderIndex, TypeIndex,
//                             StanceTypes, FormIndex, QueuePos, diplomacy, order flags
//
// No game balance data appears here; that lives in schema/live/env-typecaps.bin.
#![allow(dead_code)]

/// Total TypeIndex universe. `NUM_TYPES` in the PDB enum.
pub const NUM_TYPES: usize = 806;
pub const NUM_GOODTYPES: usize = 50;
pub const NUM_UNITTYPES: usize = 352;
pub const NUM_GAIATYPES: usize = 12;
pub const NUM_BUILDTYPES: usize = 129;
/// The six gathered resources: FOOD TIMBER WEALTH KNOWLEDGE METAL OIL.
pub const NUM_COMMON: usize = 6;
pub const UNIT_TYPE_BASE: usize = 50;
pub const GAIA_TYPE_BASE: usize = 402;
pub const BUILD_TYPE_BASE: usize = 414;

/// Owner slots iterated by `Objects::process_all`, which rotates the start each
/// frame as `(frame + i) % 10` [measured]. Eight are players; the remainder are
/// gaia/neutral slots.
pub const NUM_OWNER_SLOTS: usize = 10;
pub const NUM_PLAYERS: usize = 8;

/// Milliseconds per simulation tick at each speed setting, from
/// `TurnControl::timings` at 0x00AFC4A4 [measured]. Index 1 is Normal.
pub const TICK_MS: [u32; 5] = [200, 125, 67, 50, 1];
pub const TICK_MS_NORMAL: u32 = TICK_MS[2];

/// `UnitOrder` subclasses, the engine's own order taxonomy.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u16)]
pub enum OrderIndex {
    None = 0,
    MoveTo = 1,
    AttackTo = 2,
    ExploreTo = 3,
    FleeTo = 4,
    Patrol = 5,
    BuildAt = 6,
    Gather = 7,
    BoardShip = 8,
    AwaitBoard = 9,
    Attack = 10,
    Follow = 11,
    Guard = 12,
    Repair = 13,
    CastSpell = 14,
    TradeRoute = 15,
    Strafe = 16,
    AirPatrol = 17,
    ChangeForm = 18,
    GroupMove = 19,
    GroupAttack = 20,
    GroupAttackTo = 21,
    GroupPatrol = 22,
    AttackGround = 23,
    AirAttackGround = 24,
    SpecialAnim = 25,
    Garrison = 26,
    Think = 27,
}

/// `StanceTypes`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Stance {
    StanceCombat = 0,
    StanceWorker = 1,
    StanceCaster = 2,
    StancePacker = 3,
}

/// `QueuePos`, the `queued` field of every queued command.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum QueuePos {
    QueueFirst = 0,
    QueueLast = 1,
    QueueNew = 2,
}

/// Diplomatic state; `TreatyCommand::treaty` / `DeclareCommand::treaty`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Diplo {
    War = 0,
    Peace = 1,
    Ally = 2,
}

/// `FormIndex`. `Line..ELeft` are the five real formations; the rest are
/// selectable extras and the 253..255 values are relative selectors.
pub const FORMS: [(&str, u8); 10] = [
    ("FORM_LINE", 0),
    ("FORM_REFUSED", 1),
    ("FORM_ENVELOP", 2),
    ("FORM_E_RIGHT", 3),
    ("FORM_E_LEFT", 4),
    ("FORM_SPARSE", 5),
    ("FORM_SQUARE", 6),
    ("FORM_WEDGE", 7),
    ("FORM_COLUMN", 8),
    ("FORM_MOB", 9),
];

/// `ORDER_*` bit flags carried in the `orders` byte of the move commands.
pub const ORDER_FLAGS: [(&str, u32); 8] = [
    ("ORDER_PATHED", 1),
    ("ORDER_FLEEING", 2),
    ("ORDER_GROUP", 4),
    ("ORDER_DEFENSIVE", 8),
    ("ORDER_MORE_WORK", 16),
    ("ORDER_DISEMBARK", 32),
    ("ORDER_PUSHED", 64),
    ("ORDER_FACING_TARGET", 128),
];

/// Terrain coordinate flags (`FLAG_*`), the natural source of spatial planes.
pub const TERRAIN_FLAGS: [(&str, u32); 18] = [
    ("FLAG_GOODY", 32768),
    ("FLAG_BUILDING", 16384),
    ("FLAG_RIVERBED", 8192),
    ("FLAG_TEST_FOG", 8192),
    ("FLAG_RIVER", 4096),
    ("FLAG_OIL", 2048),
    ("FLAG_ORIGINAL_COAST", 1024),
    ("FLAG_NEAR_BLOCKING", 512),
    ("FLAG_HALFLAND", 256),
    ("FLAG_ROAD", 128),
    ("FLAG_CLIFF", 64),
    ("FLAG_FOREST", 32),
    ("FLAG_MOUNTAIN", 16),
    ("FLAG_ROCK", 8),
    ("FLAG_COAST", 4),
    ("FLAG_RIVER_VALLEY", 2),
    ("FLAG_DEAD_BUILD", 2),
    ("FLAG_RESOURCE", 1),
];

/// Parameter heads of the unit action group, in array order.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(usize)]
pub enum UnitHead {
    Verb = 0,
    TargetX = 1,
    TargetY = 2,
    TargetEntity = 3,
    Type = 4,
    QueuePos = 5,
    Stance = 6,
    Form = 7,
    OrderMods = 8,
    Count = 9,
}
pub const N_UNIT_HEADS: usize = 10;
pub const UNIT_HEAD_NAMES: [&str; 10] = [
    "Verb",
    "TargetX",
    "TargetY",
    "TargetEntity",
    "Type",
    "QueuePos",
    "Stance",
    "Form",
    "OrderMods",
    "Count",
];

/// Parameter heads of the player action group, in array order.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(usize)]
pub enum PlayerHead {
    Verb = 0,
    TargetPlayer = 1,
    Good = 2,
    Amount = 3,
    Treaty = 4,
}
pub const N_PLAYER_HEADS: usize = 5;
pub const PLAYER_HEAD_NAMES: [&str; 5] = ["Verb", "TargetPlayer", "Good", "Amount", "Treaty"];

/// One agent-emittable verb: the engine opcode it becomes, and which heads
/// supply its parameters.
pub struct VerbDef {
    pub name: &'static str,
    /// `CommandTypes` opcode this verb serialises to.
    pub opcode: u8,
    /// `sizeof` the wire struct, from the PDB.
    pub wire_size: u16,
    /// Bit i set => head i of this group is read for this verb.
    pub heads: u32,
    /// Command fields no head supplies; each is a documented gap.
    pub unsupplied: &'static [&'static str],
}

/// 33 unit verbs. Index 0 of the Verb head is NOOP, so the
/// head size is 33 + 1.
pub const UNIT_VERBS: [VerbDef; 33] = [
    VerbDef {
        name: "STANCE",
        opcode: 2,
        wire_size: 5,
        heads: 0x41,
        unsupplied: &[],
    }, // StanceCommand
    VerbDef {
        name: "FORM",
        opcode: 3,
        wire_size: 13,
        heads: 0xa1,
        unsupplied: &[],
    }, // FormCommand
    VerbDef {
        name: "ATTACK",
        opcode: 4,
        wire_size: 17,
        heads: 0x29,
        unsupplied: &["ignore"],
    }, // AttackCommand
    VerbDef {
        name: "SIEGE_ATTACK",
        opcode: 5,
        wire_size: 13,
        heads: 0x29,
        unsupplied: &[],
    }, // SiegeAttackCommand
    VerbDef {
        name: "SWARM_AROUND",
        opcode: 6,
        wire_size: 17,
        heads: 0x129,
        unsupplied: &[],
    }, // SwarmAroundCommand
    VerbDef {
        name: "MOVE_TO",
        opcode: 7,
        wire_size: 22,
        heads: 0x1a7,
        unsupplied: &["set_angle", "angle", "width", "disembark"],
    }, // MoveToCommand
    VerbDef {
        name: "MOVE_NEAR",
        opcode: 8,
        wire_size: 26,
        heads: 0x1a7,
        unsupplied: &["tolerance", "set_angle", "angle", "width", "disembark"],
    }, // MoveNearCommand
    VerbDef {
        name: "ATTACK_GROUND",
        opcode: 9,
        wire_size: 10,
        heads: 0x27,
        unsupplied: &[],
    }, // AttackGroundCommand
    VerbDef {
        name: "PATROL",
        opcode: 10,
        wire_size: 10,
        heads: 0x27,
        unsupplied: &[],
    }, // PatrolCommand
    VerbDef {
        name: "LAUNCH_PATROL",
        opcode: 11,
        wire_size: 25,
        heads: 0x27,
        unsupplied: &["shift", "ctrl", "alt"],
    }, // LaunchPatrolCommand
    VerbDef {
        name: "HALT",
        opcode: 12,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // HaltCommand
    VerbDef {
        name: "TRANSPORT",
        opcode: 13,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // TransportCommand
    VerbDef {
        name: "SET_TRANSPORT",
        opcode: 14,
        wire_size: 5,
        heads: 0x1,
        unsupplied: &["flag"],
    }, // SetTransportCommand
    VerbDef {
        name: "BOARD_SHIP",
        opcode: 15,
        wire_size: 9,
        heads: 0x29,
        unsupplied: &[],
    }, // BoardShipCommand
    VerbDef {
        name: "REPAIR",
        opcode: 16,
        wire_size: 13,
        heads: 0x29,
        unsupplied: &[],
    }, // RepairCommand
    VerbDef {
        name: "TRADE",
        opcode: 17,
        wire_size: 21,
        heads: 0x29,
        unsupplied: &["oxx", "whose"],
    }, // TradeCommand
    VerbDef {
        name: "CITY_GATHER",
        opcode: 18,
        wire_size: 9,
        heads: 0x21,
        unsupplied: &["t"],
    }, // CityGatherCommand
    VerbDef {
        name: "GATHER",
        opcode: 19,
        wire_size: 9,
        heads: 0x29,
        unsupplied: &[],
    }, // GatherCommand
    VerbDef {
        name: "GARRISON",
        opcode: 20,
        wire_size: 13,
        heads: 0x29,
        unsupplied: &[],
    }, // GarrisonCommand
    VerbDef {
        name: "DISBAND",
        opcode: 21,
        wire_size: 5,
        heads: 0x1,
        unsupplied: &["all"],
    }, // DisbandCommand
    VerbDef {
        name: "GATHER_POINT",
        opcode: 22,
        wire_size: 17,
        heads: 0x7,
        unsupplied: &["action", "add_to_end"],
    }, // GatherPointCommand
    VerbDef {
        name: "SPELL",
        opcode: 23,
        wire_size: 21,
        heads: 0x1f,
        unsupplied: &[],
    }, // SpellCommand
    VerbDef {
        name: "QUEUE_UP",
        opcode: 24,
        wire_size: 9,
        heads: 0x211,
        unsupplied: &[],
    }, // QueueUpCommand
    VerbDef {
        name: "BUILD",
        opcode: 25,
        wire_size: 25,
        heads: 0x37,
        unsupplied: &[],
    }, // BuildCommand
    VerbDef {
        name: "EJECTALL",
        opcode: 26,
        wire_size: 17,
        heads: 0x1,
        unsupplied: &["back_to_work", "eject_o", "eject_who"],
    }, // EjectAllCommand
    VerbDef {
        name: "FLIGHT",
        opcode: 28,
        wire_size: 25,
        heads: 0x109,
        unsupplied: &["shift", "ctrl", "alt"],
    }, // FlightCommand
    VerbDef {
        name: "STOP_SPELL",
        opcode: 29,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // StopSpellCommand
    VerbDef {
        name: "FOLLOW",
        opcode: 30,
        wire_size: 13,
        heads: 0x29,
        unsupplied: &[],
    }, // FollowCommand
    VerbDef {
        name: "GUARD",
        opcode: 31,
        wire_size: 13,
        heads: 0x29,
        unsupplied: &[],
    }, // GuardCommand
    VerbDef {
        name: "RECALL",
        opcode: 35,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // RecallCommand
    VerbDef {
        name: "SCRAMBLE",
        opcode: 36,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // ScrambleCommand
    VerbDef {
        name: "UNQUEUE",
        opcode: 48,
        wire_size: 15,
        heads: 0x11,
        unsupplied: &["o", "uid"],
    }, // UnqueueCommand
    VerbDef {
        name: "COME_OUT",
        opcode: 49,
        wire_size: 11,
        heads: 0x1,
        unsupplied: &["o", "uid"],
    }, // ComeOutCommand
];
pub const N_UNIT_VERBS: usize = 33;

/// 16 player verbs. Index 0 of the Verb head is NOOP, so the
/// head size is 16 + 1.
pub const PLAYER_VERBS: [VerbDef; 16] = [
    VerbDef {
        name: "ALARM",
        opcode: 27,
        wire_size: 1,
        heads: 0x1,
        unsupplied: &[],
    }, // AlarmCommand
    VerbDef {
        name: "UNITMASK",
        opcode: 32,
        wire_size: 9,
        heads: 0x1,
        unsupplied: &["unitmask", "set"],
    }, // UnitmaskCommand
    VerbDef {
        name: "BUILDMASK",
        opcode: 33,
        wire_size: 9,
        heads: 0x1,
        unsupplied: &["buildmask", "set"],
    }, // BuildmaskCommand
    VerbDef {
        name: "TREATY",
        opcode: 37,
        wire_size: 13,
        heads: 0x13,
        unsupplied: &[],
    }, // TreatyCommand
    VerbDef {
        name: "DECLARE",
        opcode: 38,
        wire_size: 13,
        heads: 0x13,
        unsupplied: &[],
    }, // DeclareCommand
    VerbDef {
        name: "CLEAR_TRIBUTES",
        opcode: 39,
        wire_size: 9,
        heads: 0x3,
        unsupplied: &[],
    }, // ClearTributesCommand
    VerbDef {
        name: "CLEAR_ALL",
        opcode: 40,
        wire_size: 9,
        heads: 0x3,
        unsupplied: &[],
    }, // ClearAllCommand
    VerbDef {
        name: "ACCEPT",
        opcode: 41,
        wire_size: 9,
        heads: 0x3,
        unsupplied: &[],
    }, // AcceptCommand
    VerbDef {
        name: "REJECT",
        opcode: 42,
        wire_size: 9,
        heads: 0x3,
        unsupplied: &[],
    }, // RejectCommand
    VerbDef {
        name: "TRIBUTE",
        opcode: 43,
        wire_size: 17,
        heads: 0xf,
        unsupplied: &[],
    }, // TributeCommand
    VerbDef {
        name: "DEMAND_TRIBUTE",
        opcode: 44,
        wire_size: 17,
        heads: 0xf,
        unsupplied: &[],
    }, // DemandTributeCommand
    VerbDef {
        name: "PROPOSE_ATTACK",
        opcode: 45,
        wire_size: 17,
        heads: 0x3,
        unsupplied: &["whose", "onoff"],
    }, // ProposeAttackCommand
    VerbDef {
        name: "BUY",
        opcode: 46,
        wire_size: 13,
        heads: 0x7,
        unsupplied: &["flags"],
    }, // BuyCommand
    VerbDef {
        name: "SELL",
        opcode: 47,
        wire_size: 13,
        heads: 0x7,
        unsupplied: &["flags"],
    }, // SellCommand
    VerbDef {
        name: "RESIGN",
        opcode: 70,
        wire_size: 5,
        heads: 0x1,
        unsupplied: &["play"],
    }, // ResignCommand
    VerbDef {
        name: "LEADER_OPTIONS",
        opcode: 73,
        wire_size: 33,
        heads: 0x1,
        unsupplied: &["leader_option"],
    }, // LeaderOptionsCommand
];
pub const N_PLAYER_VERBS: usize = 16;

/// Indices into `UNIT_VERBS`, +1 to get the Verb head value (0 = NOOP).
pub mod uv {
    pub const STANCE: usize = 0;
    pub const FORM: usize = 1;
    pub const ATTACK: usize = 2;
    pub const SIEGE_ATTACK: usize = 3;
    pub const SWARM_AROUND: usize = 4;
    pub const MOVE_TO: usize = 5;
    pub const MOVE_NEAR: usize = 6;
    pub const ATTACK_GROUND: usize = 7;
    pub const PATROL: usize = 8;
    pub const LAUNCH_PATROL: usize = 9;
    pub const HALT: usize = 10;
    pub const TRANSPORT: usize = 11;
    pub const SET_TRANSPORT: usize = 12;
    pub const BOARD_SHIP: usize = 13;
    pub const REPAIR: usize = 14;
    pub const TRADE: usize = 15;
    pub const CITY_GATHER: usize = 16;
    pub const GATHER: usize = 17;
    pub const GARRISON: usize = 18;
    pub const DISBAND: usize = 19;
    pub const GATHER_POINT: usize = 20;
    pub const SPELL: usize = 21;
    pub const QUEUE_UP: usize = 22;
    pub const BUILD: usize = 23;
    pub const EJECTALL: usize = 24;
    pub const FLIGHT: usize = 25;
    pub const STOP_SPELL: usize = 26;
    pub const FOLLOW: usize = 27;
    pub const GUARD: usize = 28;
    pub const RECALL: usize = 29;
    pub const SCRAMBLE: usize = 30;
    pub const UNQUEUE: usize = 31;
    pub const COME_OUT: usize = 32;
}
pub mod pv {
    pub const ALARM: usize = 0;
    pub const UNITMASK: usize = 1;
    pub const BUILDMASK: usize = 2;
    pub const TREATY: usize = 3;
    pub const DECLARE: usize = 4;
    pub const CLEAR_TRIBUTES: usize = 5;
    pub const CLEAR_ALL: usize = 6;
    pub const ACCEPT: usize = 7;
    pub const REJECT: usize = 8;
    pub const TRIBUTE: usize = 9;
    pub const DEMAND_TRIBUTE: usize = 10;
    pub const PROPOSE_ATTACK: usize = 11;
    pub const BUY: usize = 12;
    pub const SELL: usize = 13;
    pub const RESIGN: usize = 14;
    pub const LEADER_OPTIONS: usize = 15;
}

/// Opcodes classified SELECTION: not agent actions.
pub const SELECTION_OPCODES: [(u8, &str); 2] = [(0, "GROUP"), (34, "HOTKEY")];
/// Opcodes classified UI: not agent actions.
pub const UI_OPCODES: [(u8, &str); 8] = [
    (50, "PING"),
    (51, "SPLINE"),
    (68, "CHAT"),
    (69, "CHAT_SET"),
    (72, "CAMERA"),
    (75, "RENAME_CITY"),
    (78, "CONSOLE_CMD"),
    (79, "PLAYER_SPEED"),
];
/// Opcodes classified ADMIN: not agent actions.
pub const ADMIN_OPCODES: [(u8, &str); 14] = [
    (1, "BEGIN"),
    (52, "SPEED_SET"),
    (53, "SPEED_UP"),
    (54, "SPEED_DOWN"),
    (55, "MP_LOG"),
    (56, "CHECK_RANDOM"),
    (57, "CHECK_SUMS"),
    (58, "NEXT_CHECK_SUM"),
    (71, "QUIT"),
    (74, "TURN_DATA"),
    (76, "PAUSE"),
    (77, "CANNON_TIME"),
    (80, "UNGRACEFUL_PLAYER_DROP"),
    (81, "MARWAN"),
];
/// Opcodes classified CHEAT: not agent actions.
pub const CHEAT_OPCODES: [(u8, &str); 9] = [
    (59, "CHEAT_VIEW_ALL"),
    (60, "CHEAT_GIVE_TECHS"),
    (61, "CHEAT_ZERO_TECHS"),
    (62, "CHEAT_AI_SPEED_INCREASE"),
    (63, "CHEAT_AI_SPEED_NORMAL"),
    (64, "CHEAT_AI_TOGGLE"),
    (65, "CHEAT_INCREASE_BUCKETS"),
    (66, "CHEAT_ZERO_BUCKETS"),
    (67, "CHEAT_INIT_UNIT"),
];
