//! GENERATED by `web/tools/gen-wire.mjs` from `schema/command-wire.json`. Do not edit.
//!
//! The wasm side of the engine's command wire format. The browser encodes a command with
//! the generated JS codec, posts the raw bytes, and this module reads the fields back out
//! at the derived offsets — so the byte stream between a click and the simulation is the
//! engine's own packet layout, not an envelope invented for this app.
//!
//! Field widths are reconstructed from consecutive offsets plus the struct's wire size;
//! the generator explains why that is exact here.

/// Opcode constants, named after the struct each dispatches to.
pub mod op {
    /// `GroupCommand` — 5 bytes, `CommandPackage::process_group`.
    pub const GROUP: u8 = 0x00;
    /// `BeginCommand` — 1 bytes, `CommandPackage::process_begin`.
    pub const BEGIN: u8 = 0x01;
    /// `StanceCommand` — 5 bytes, `CommandPackage::process_stance`.
    pub const STANCE: u8 = 0x02;
    /// `FormCommand` — 13 bytes, `CommandPackage::process_form`.
    pub const FORM: u8 = 0x03;
    /// `AttackCommand` — 17 bytes, `CommandPackage::process_attack`.
    pub const ATTACK: u8 = 0x04;
    /// `SiegeAttackCommand` — 13 bytes, `CommandPackage::process_siege_attack`.
    pub const SIEGE_ATTACK: u8 = 0x05;
    /// `SwarmAroundCommand` — 17 bytes, `CommandPackage::process_swarm_around`.
    pub const SWARM_AROUND: u8 = 0x06;
    /// `MoveToCommand` — 22 bytes, `CommandPackage::process_move_to`.
    pub const MOVE_TO: u8 = 0x07;
    /// `MoveNearCommand` — 26 bytes, `CommandPackage::process_move_near`.
    pub const MOVE_NEAR: u8 = 0x08;
    /// `AttackGroundCommand` — 10 bytes, `CommandPackage::process_attack_ground`.
    pub const ATTACK_GROUND: u8 = 0x09;
    /// `PatrolCommand` — 10 bytes, `CommandPackage::process_patrol`.
    pub const PATROL: u8 = 0x0a;
    /// `LaunchPatrolCommand` — 25 bytes, `CommandPackage::process_launch_patrol`.
    pub const LAUNCH_PATROL: u8 = 0x0b;
    /// `HaltCommand` — 1 bytes, `CommandPackage::process_halt`.
    pub const HALT: u8 = 0x0c;
    /// `TransportCommand` — 1 bytes, `CommandPackage::process_transport`.
    pub const TRANSPORT: u8 = 0x0d;
    /// `SetTransportCommand` — 5 bytes, `CommandPackage::process_set_transport`.
    pub const SET_TRANSPORT: u8 = 0x0e;
    /// `BoardShipCommand` — 9 bytes, `CommandPackage::process_board_ship`.
    pub const BOARD_SHIP: u8 = 0x0f;
    /// `RepairCommand` — 13 bytes, `CommandPackage::process_repair`.
    pub const REPAIR: u8 = 0x10;
    /// `TradeCommand` — 21 bytes, `CommandPackage::process_trade`.
    pub const TRADE: u8 = 0x11;
    /// `CityGatherCommand` — 9 bytes, `CommandPackage::process_city_gather`.
    pub const CITY_GATHER: u8 = 0x12;
    /// `GatherCommand` — 9 bytes, `CommandPackage::process_gather`.
    pub const GATHER: u8 = 0x13;
    /// `GarrisonCommand` — 13 bytes, `CommandPackage::process_garrison`.
    pub const GARRISON: u8 = 0x14;
    /// `DisbandCommand` — 5 bytes, `CommandPackage::process_disband`.
    pub const DISBAND: u8 = 0x15;
    /// `GatherPointCommand` — 17 bytes, `CommandPackage::process_gather_point`.
    pub const GATHER_POINT: u8 = 0x16;
    /// `SpellCommand` — 21 bytes, `CommandPackage::process_spell`.
    pub const SPELL: u8 = 0x17;
    /// `QueueUpCommand` — 9 bytes, `CommandPackage::process_queue_up`.
    pub const QUEUE_UP: u8 = 0x18;
    /// `BuildCommand` — 25 bytes, `CommandPackage::process_build`.
    pub const BUILD: u8 = 0x19;
    /// `EjectAllCommand` — 17 bytes, `CommandPackage::process_eject_all`.
    pub const EJECT_ALL: u8 = 0x1a;
    /// `AlarmCommand` — 1 bytes, `CommandPackage::process_alarm`.
    pub const ALARM: u8 = 0x1b;
    /// `FlightCommand` — 25 bytes, `CommandPackage::process_flight`.
    pub const FLIGHT: u8 = 0x1c;
    /// `StopSpellCommand` — 1 bytes, `CommandPackage::process_stop_spell`.
    pub const STOP_SPELL: u8 = 0x1d;
    /// `FollowCommand` — 13 bytes, `CommandPackage::process_follow`.
    pub const FOLLOW: u8 = 0x1e;
    /// `GuardCommand` — 13 bytes, `CommandPackage::process_guard`.
    pub const GUARD: u8 = 0x1f;
    /// `UnitmaskCommand` — 9 bytes, `CommandPackage::process_unitmask`.
    pub const UNITMASK: u8 = 0x20;
    /// `BuildmaskCommand` — 9 bytes, `CommandPackage::process_buildmask`.
    pub const BUILDMASK: u8 = 0x21;
    /// `HotKeyCommand` — 25 bytes, `CommandPackage::process_hotkey`.
    pub const HOT_KEY: u8 = 0x22;
    /// `RecallCommand` — 1 bytes, `CommandPackage::process_recall`.
    pub const RECALL: u8 = 0x23;
    /// `ScrambleCommand` — 1 bytes, `CommandPackage::process_scramble`.
    pub const SCRAMBLE: u8 = 0x24;
    /// `TreatyCommand` — 13 bytes, `CommandPackage::process_treaty`.
    pub const TREATY: u8 = 0x25;
    /// `DeclareCommand` — 13 bytes, `CommandPackage::process_declare`.
    pub const DECLARE: u8 = 0x26;
    /// `ClearTributesCommand` — 9 bytes, `CommandPackage::process_clear_tributes`.
    pub const CLEAR_TRIBUTES: u8 = 0x27;
    /// `ClearAllCommand` — 9 bytes, `CommandPackage::process_clear_all`.
    pub const CLEAR_ALL: u8 = 0x28;
    /// `AcceptCommand` — 9 bytes, `CommandPackage::process_accept`.
    pub const ACCEPT: u8 = 0x29;
    /// `RejectCommand` — 9 bytes, `CommandPackage::process_reject`.
    pub const REJECT: u8 = 0x2a;
    /// `TributeCommand` — 17 bytes, `CommandPackage::process_tribute`.
    pub const TRIBUTE: u8 = 0x2b;
    /// `DemandTributeCommand` — 17 bytes, `CommandPackage::process_demand_tribute`.
    pub const DEMAND_TRIBUTE: u8 = 0x2c;
    /// `ProposeAttackCommand` — 17 bytes, `CommandPackage::process_propose_attack`.
    pub const PROPOSE_ATTACK: u8 = 0x2d;
    /// `BuyCommand` — 13 bytes, `CommandPackage::process_buy`.
    pub const BUY: u8 = 0x2e;
    /// `SellCommand` — 13 bytes, `CommandPackage::process_sell`.
    pub const SELL: u8 = 0x2f;
    /// `UnqueueCommand` — 15 bytes, `CommandPackage::process_unqueue`.
    pub const UNQUEUE: u8 = 0x30;
    /// `ComeOutCommand` — 11 bytes, `CommandPackage::process_come_out`.
    pub const COME_OUT: u8 = 0x31;
    /// `PingCommand` — 9 bytes, `CommandPackage::process_ping`.
    pub const PING: u8 = 0x32;
    /// `SplineCommand` — 14 bytes, `CommandPackage::process_spline`.
    pub const SPLINE: u8 = 0x33;
    /// `SpeedSetCommand` — 5 bytes, `CommandPackage::process_speed_set`.
    pub const SPEED_SET: u8 = 0x34;
    /// `SpeedUpCommand` — 1 bytes, `CommandPackage::process_speed_up`.
    pub const SPEED_UP: u8 = 0x35;
    /// `SpeedDownCommand` — 1 bytes, `CommandPackage::process_speed_down`.
    pub const SPEED_DOWN: u8 = 0x36;
    /// `MPLogCommand` — 1 bytes, `CommandPackage::process_mp_log`.
    pub const MPLOG: u8 = 0x37;
    /// `CheckRandomCommand` — 5 bytes, `CommandPackage::process_check_random`.
    pub const CHECK_RANDOM: u8 = 0x38;
    /// `CheckSumsCommand` — 65 bytes, `CommandPackage::process_check_sums`.
    pub const CHECK_SUMS: u8 = 0x39;
    /// `NextCheckSumCommand` — 6 bytes, `CommandPackage::process_next_check_sum`.
    pub const NEXT_CHECK_SUM: u8 = 0x3a;
    /// `CheatViewAllCommand` — 5 bytes, `CommandPackage::process_cheat_view_all`.
    pub const CHEAT_VIEW_ALL: u8 = 0x3b;
    /// `CheatGiveTechsCommand` — 5 bytes, `CommandPackage::process_cheat_give_techs`.
    pub const CHEAT_GIVE_TECHS: u8 = 0x3c;
    /// `CheatZeroTechsCommand` — 5 bytes, `CommandPackage::process_cheat_zero_techs`.
    pub const CHEAT_ZERO_TECHS: u8 = 0x3d;
    /// `CheatAISpeedIncreaseCommand` — 1 bytes, `CommandPackage::process_cheat_ai_speed_increase`.
    pub const CHEAT_AISPEED_INCREASE: u8 = 0x3e;
    /// `CheatAISpeedNormalCommand` — 1 bytes, `CommandPackage::process_cheat_ai_speed_normal`.
    pub const CHEAT_AISPEED_NORMAL: u8 = 0x3f;
    /// `CheatAIToggleCommand` — 1 bytes, `CommandPackage::process_cheat_ai_toggle`.
    pub const CHEAT_AITOGGLE: u8 = 0x40;
    /// `CheatIncreaseBucketsCommand` — 5 bytes, `CommandPackage::process_cheat_increase_buckets`.
    pub const CHEAT_INCREASE_BUCKETS: u8 = 0x41;
    /// `CheatZeroBucketsCommand` — 5 bytes, `CommandPackage::process_cheat_zero_buckets`.
    pub const CHEAT_ZERO_BUCKETS: u8 = 0x42;
    /// `CheatInitUnitCommand` — 17 bytes, `CommandPackage::process_cheat_init_unit`.
    pub const CHEAT_INIT_UNIT: u8 = 0x43;
    /// `ChatCommand` — 19 bytes, `CommandPackage::process_chat`.
    pub const CHAT: u8 = 0x44;
    /// `ChatSetCommand` — 9 bytes, `CommandPackage::process_chat_set`.
    pub const CHAT_SET: u8 = 0x45;
    /// `ResignCommand` — 5 bytes, `CommandPackage::process_resign`.
    pub const RESIGN: u8 = 0x46;
    /// `QuitCommand` — 7 bytes, `CommandPackage::process_quit`.
    pub const QUIT: u8 = 0x47;
    /// `CameraCommand` — 10 bytes, `CommandPackage::process_camera`.
    pub const CAMERA: u8 = 0x48;
    /// `LeaderOptionsCommand` — 33 bytes, `CommandPackage::process_leader_options`.
    pub const LEADER_OPTIONS: u8 = 0x49;
    /// `TurnDataCommand` — 11 bytes, `CommandPackage::process_turn_data`.
    pub const TURN_DATA: u8 = 0x4a;
    /// `RenameCityCommand` — 53 bytes, `CommandPackage::process_rename_city`.
    pub const RENAME_CITY: u8 = 0x4b;
    /// `PauseCommand` — 2 bytes, `CommandPackage::process_pause`.
    pub const PAUSE: u8 = 0x4c;
    /// `CannonTimeCommand` — 2 bytes, `CommandPackage::process_cannon_time`.
    pub const CANNON_TIME: u8 = 0x4d;
    /// `ConsoleCmdCommand` — 521 bytes, `CommandPackage::process_console_cmd`.
    pub const CONSOLE_CMD: u8 = 0x4e;
    /// `PlayerSpeedCommand` — 9 bytes, `CommandPackage::process_player_speed`.
    pub const PLAYER_SPEED: u8 = 0x4f;
    /// `UngracefulPlayerDrop` — 3 bytes, `CommandPackage::process_ungraceful_player_drop`.
    pub const UNGRACEFUL_PLAYER_DROP: u8 = 0x50;
    /// `MarwanCommand` — 2 bytes, `CommandPackage::process_marwan`.
    pub const MARWAN: u8 = 0x51;
}

/// Declared wire size by opcode; `None` where the opcode is unused.
pub const SIZE: [Option<u16>; 256] = {
    let mut t = [None; 256];
    t[0x00] = Some(5);
    t[0x01] = Some(1);
    t[0x02] = Some(5);
    t[0x03] = Some(13);
    t[0x04] = Some(17);
    t[0x05] = Some(13);
    t[0x06] = Some(17);
    t[0x07] = Some(22);
    t[0x08] = Some(26);
    t[0x09] = Some(10);
    t[0x0a] = Some(10);
    t[0x0b] = Some(25);
    t[0x0c] = Some(1);
    t[0x0d] = Some(1);
    t[0x0e] = Some(5);
    t[0x0f] = Some(9);
    t[0x10] = Some(13);
    t[0x11] = Some(21);
    t[0x12] = Some(9);
    t[0x13] = Some(9);
    t[0x14] = Some(13);
    t[0x15] = Some(5);
    t[0x16] = Some(17);
    t[0x17] = Some(21);
    t[0x18] = Some(9);
    t[0x19] = Some(25);
    t[0x1a] = Some(17);
    t[0x1b] = Some(1);
    t[0x1c] = Some(25);
    t[0x1d] = Some(1);
    t[0x1e] = Some(13);
    t[0x1f] = Some(13);
    t[0x20] = Some(9);
    t[0x21] = Some(9);
    t[0x22] = Some(25);
    t[0x23] = Some(1);
    t[0x24] = Some(1);
    t[0x25] = Some(13);
    t[0x26] = Some(13);
    t[0x27] = Some(9);
    t[0x28] = Some(9);
    t[0x29] = Some(9);
    t[0x2a] = Some(9);
    t[0x2b] = Some(17);
    t[0x2c] = Some(17);
    t[0x2d] = Some(17);
    t[0x2e] = Some(13);
    t[0x2f] = Some(13);
    t[0x30] = Some(15);
    t[0x31] = Some(11);
    t[0x32] = Some(9);
    t[0x33] = Some(14);
    t[0x34] = Some(5);
    t[0x35] = Some(1);
    t[0x36] = Some(1);
    t[0x37] = Some(1);
    t[0x38] = Some(5);
    t[0x39] = Some(65);
    t[0x3a] = Some(6);
    t[0x3b] = Some(5);
    t[0x3c] = Some(5);
    t[0x3d] = Some(5);
    t[0x3e] = Some(1);
    t[0x3f] = Some(1);
    t[0x40] = Some(1);
    t[0x41] = Some(5);
    t[0x42] = Some(5);
    t[0x43] = Some(17);
    t[0x44] = Some(19);
    t[0x45] = Some(9);
    t[0x46] = Some(5);
    t[0x47] = Some(7);
    t[0x48] = Some(10);
    t[0x49] = Some(33);
    t[0x4a] = Some(11);
    t[0x4b] = Some(53);
    t[0x4c] = Some(2);
    t[0x4d] = Some(2);
    t[0x4e] = Some(521);
    t[0x4f] = Some(9);
    t[0x50] = Some(3);
    t[0x51] = Some(2);
    t
};

/// Struct name by opcode, for diagnostics.
pub fn struct_name(op: u8) -> &'static str {
    match op {
        0x00 => "GroupCommand",
        0x01 => "BeginCommand",
        0x02 => "StanceCommand",
        0x03 => "FormCommand",
        0x04 => "AttackCommand",
        0x05 => "SiegeAttackCommand",
        0x06 => "SwarmAroundCommand",
        0x07 => "MoveToCommand",
        0x08 => "MoveNearCommand",
        0x09 => "AttackGroundCommand",
        0x0a => "PatrolCommand",
        0x0b => "LaunchPatrolCommand",
        0x0c => "HaltCommand",
        0x0d => "TransportCommand",
        0x0e => "SetTransportCommand",
        0x0f => "BoardShipCommand",
        0x10 => "RepairCommand",
        0x11 => "TradeCommand",
        0x12 => "CityGatherCommand",
        0x13 => "GatherCommand",
        0x14 => "GarrisonCommand",
        0x15 => "DisbandCommand",
        0x16 => "GatherPointCommand",
        0x17 => "SpellCommand",
        0x18 => "QueueUpCommand",
        0x19 => "BuildCommand",
        0x1a => "EjectAllCommand",
        0x1b => "AlarmCommand",
        0x1c => "FlightCommand",
        0x1d => "StopSpellCommand",
        0x1e => "FollowCommand",
        0x1f => "GuardCommand",
        0x20 => "UnitmaskCommand",
        0x21 => "BuildmaskCommand",
        0x22 => "HotKeyCommand",
        0x23 => "RecallCommand",
        0x24 => "ScrambleCommand",
        0x25 => "TreatyCommand",
        0x26 => "DeclareCommand",
        0x27 => "ClearTributesCommand",
        0x28 => "ClearAllCommand",
        0x29 => "AcceptCommand",
        0x2a => "RejectCommand",
        0x2b => "TributeCommand",
        0x2c => "DemandTributeCommand",
        0x2d => "ProposeAttackCommand",
        0x2e => "BuyCommand",
        0x2f => "SellCommand",
        0x30 => "UnqueueCommand",
        0x31 => "ComeOutCommand",
        0x32 => "PingCommand",
        0x33 => "SplineCommand",
        0x34 => "SpeedSetCommand",
        0x35 => "SpeedUpCommand",
        0x36 => "SpeedDownCommand",
        0x37 => "MPLogCommand",
        0x38 => "CheckRandomCommand",
        0x39 => "CheckSumsCommand",
        0x3a => "NextCheckSumCommand",
        0x3b => "CheatViewAllCommand",
        0x3c => "CheatGiveTechsCommand",
        0x3d => "CheatZeroTechsCommand",
        0x3e => "CheatAISpeedIncreaseCommand",
        0x3f => "CheatAISpeedNormalCommand",
        0x40 => "CheatAIToggleCommand",
        0x41 => "CheatIncreaseBucketsCommand",
        0x42 => "CheatZeroBucketsCommand",
        0x43 => "CheatInitUnitCommand",
        0x44 => "ChatCommand",
        0x45 => "ChatSetCommand",
        0x46 => "ResignCommand",
        0x47 => "QuitCommand",
        0x48 => "CameraCommand",
        0x49 => "LeaderOptionsCommand",
        0x4a => "TurnDataCommand",
        0x4b => "RenameCityCommand",
        0x4c => "PauseCommand",
        0x4d => "CannonTimeCommand",
        0x4e => "ConsoleCmdCommand",
        0x4f => "PlayerSpeedCommand",
        0x50 => "UngracefulPlayerDrop",
        0x51 => "MarwanCommand",
        _ => "?",
    }
}

// ---- field readers, one per field this app actually consumes ---------------------------
//
// Only the fields the simulation can honour are given readers. A reader for a field
// nothing implements would be a claim that it is modelled.

#[inline]
fn i32_at(b: &[u8], off: usize) -> i32 {
    if off + 4 > b.len() {
        return 0;
    }
    i32::from_le_bytes([b[off], b[off + 1], b[off + 2], b[off + 3]])
}
#[inline]
fn i16_at(b: &[u8], off: usize) -> i16 {
    if off + 2 > b.len() {
        return 0;
    }
    i16::from_le_bytes([b[off], b[off + 1]])
}
#[inline]
fn i8_at(b: &[u8], off: usize) -> i8 {
    if off >= b.len() {
        return 0;
    } else {
        b[off] as i8
    }
}

/// `AttackCommand` (0x04), 17 bytes.
pub mod attack {
    use super::*;
    /// field `ox`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn ox(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `whom`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn whom(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
    /// field `queued`: `QueuePos` at byte 13, 4 byte(s).
    #[inline]
    pub fn queued(b: &[u8]) -> i32 {
        i32_at(b, 13)
    }
}

/// `MoveToCommand` (0x07), 22 bytes.
pub mod move_to {
    use super::*;
    /// field `to_x`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn to_x(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `to_y`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn to_y(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
    /// field `queued`: `char` at byte 18, 1 byte(s).
    #[inline]
    pub fn queued(b: &[u8]) -> i8 {
        i8_at(b, 18)
    }
    /// field `form`: `char` at byte 19, 1 byte(s).
    #[inline]
    pub fn form(b: &[u8]) -> i8 {
        i8_at(b, 19)
    }
}

/// `PatrolCommand` (0x0a), 10 bytes.
pub mod patrol {
    use super::*;
    /// field `to_x`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn to_x(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `to_y`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn to_y(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
    /// field `queued`: `char` at byte 9, 1 byte(s).
    #[inline]
    pub fn queued(b: &[u8]) -> i8 {
        i8_at(b, 9)
    }
}

/// `GatherCommand` (0x13), 9 bytes.
pub mod gather {
    use super::*;
    /// field `ox`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn ox(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `queued`: `QueuePos` at byte 5, 4 byte(s).
    #[inline]
    pub fn queued(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
}

/// `QueueUpCommand` (0x18), 9 bytes.
pub mod queue_up {
    use super::*;
    /// field `type`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn type_(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `num`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn num(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
}

/// `BuildCommand` (0x19), 25 bytes.
pub mod build {
    use super::*;
    /// field `x`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn x(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `y`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn y(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
    /// field `x2`: `int` at byte 9, 4 byte(s).
    #[inline]
    pub fn x2(b: &[u8]) -> i32 {
        i32_at(b, 9)
    }
    /// field `y2`: `int` at byte 13, 4 byte(s).
    #[inline]
    pub fn y2(b: &[u8]) -> i32 {
        i32_at(b, 13)
    }
    /// field `type`: `int` at byte 17, 4 byte(s).
    #[inline]
    pub fn type_(b: &[u8]) -> i32 {
        i32_at(b, 17)
    }
}

/// `UnqueueCommand` (0x30), 15 bytes.
pub mod unqueue {
    use super::*;
    /// field `who`: `int` at byte 1, 4 byte(s).
    #[inline]
    pub fn who(b: &[u8]) -> i32 {
        i32_at(b, 1)
    }
    /// field `o`: `int` at byte 5, 4 byte(s).
    #[inline]
    pub fn o(b: &[u8]) -> i32 {
        i32_at(b, 5)
    }
    /// field `type`: `int` at byte 9, 4 byte(s).
    #[inline]
    pub fn type_(b: &[u8]) -> i32 {
        i32_at(b, 9)
    }
    /// field `uid`: `short` at byte 13, 2 byte(s).
    #[inline]
    pub fn uid(b: &[u8]) -> i16 {
        i16_at(b, 13)
    }
}

/// `GroupCommand` (0x00) — selection. Variable length: `num` u8, `who` i8, then `num`
/// 2-byte object indices. Hand-written because it is the one command whose length depends
/// on its contents; the entry width comes from the PDB type record
/// `GroupCommand::<unnamed-type-list> = struct { short o; }`, sizeof 2.
pub mod group {
    use super::*;
    #[inline]
    pub fn num(b: &[u8]) -> usize {
        if b.len() > 1 {
            b[1] as usize
        } else {
            0
        }
    }
    #[inline]
    pub fn who(b: &[u8]) -> i8 {
        i8_at(b, 2)
    }
    /// Object index `k`, or `None` past the end of the packet.
    #[inline]
    pub fn entry(b: &[u8], k: usize) -> Option<i16> {
        let off = 3 + k * 2;
        if off + 2 > b.len() {
            None
        } else {
            Some(i16_at(b, off))
        }
    }
}
