#!/usr/bin/env python3
"""Render provenance-ledger evidence rows from `schema/oracle-regression.json`.

`docs/provenance-ledger.md` requires every Tier-B mechanic to carry a sample count and an
input distribution. Those numbers were hand-maintained, which means they were recollections
of a run that happened once. This script prints them from the measurement file instead, so
a ledger row can be regenerated rather than remembered.

    tools/ledger-from-measurements.py                  # markdown, to stdout
    tools/ledger-from-measurements.py --check          # exit non-zero if the record is
                                                       # missing, stale, or not all-pass

It deliberately prints rather than rewriting `docs/provenance-ledger.md`: the ledger also
carries prose, caveats and refutations that no measurement produces, and a script that
overwrote them would quietly delete the most valuable part of the document.
"""

import argparse
import json
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT = os.path.join(REPO, "schema", "oracle-regression.json")
# Past this, a green record is a memory rather than a measurement.
STALE_DAYS = 30


def load(path):
    if not os.path.exists(path):
        print(f"no measurement record at {path}", file=sys.stderr)
        print(
            "Every Tier-B claim is currently unbacked by this tree. "
            "Run tools/oracle-regress.sh.",
            file=sys.stderr,
        )
        sys.exit(2)
    with open(path) as f:
        return json.load(f)


def fmt(n):
    return f"{n:,}"


def evidence_sentence(case):
    """One sentence in the ledger's house style: count, distribution, exclusions.

    Phases that differ only by a leading qualifier (the damage case runs the same
    distribution under eight seeds) are folded into one clause. Printing it eight times
    would bury the exclusions at the end of a wall of identical prose, and the exclusions
    are the part a reader must not skip.
    """
    groups = []  # [(kind, tail, total_count, n_phases, heads)]
    for p in case["phases"]:
        d = p["distribution"]
        head, tail = (d.split(": ", 1) + [None])[:2] if ": " in d else (None, d)
        if tail is None:
            head, tail = None, d
        if groups and groups[-1][0] == p["kind"] and groups[-1][1] == tail:
            g = groups[-1]
            groups[-1] = (g[0], g[1], g[2] + p["count"], g[3] + 1, g[4] + ([head] if head else []))
        else:
            groups.append((p["kind"], tail, p["count"], 1, [head] if head else []))

    parts = []
    for kind, tail, total, n, heads in groups:
        if n > 1 and heads:
            parts.append(f"{fmt(total)} {kind} over {n} × [{', '.join(heads)}] ({tail})")
        else:
            parts.append(f"{fmt(total)} {kind} ({tail})")
    s = f"**{fmt(case['trials'])} inputs, {fmt(case['mismatches'])} mismatches.** "
    s += "Distribution: " + "; ".join(parts) + "."
    if case["excluded"]:
        ex = ", ".join(f"{fmt(e['count'])} {e['reason']}" for e in case["excluded"])
        s += f" Excluded and counted, never silent: {ex}."
    return s


def render(d):
    ts = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(d["generated_unix"]))
    out = []
    out.append("<!-- generated by tools/ledger-from-measurements.py — do not hand-edit -->")
    out.append("")
    out.append(f"## Tier-B evidence, measured {ts}")
    out.append("")
    out.append(
        f"Host `{d['host']}` ({d['target']}), image sha256 `{d['image']['sha256']}`, "
        f"harness selftest **{d['harness_selftest']}**, seed `{d['seed']}`, "
        f"scale `{d['scale']}`."
    )
    s = d["summary"]
    out.append("")
    out.append(
        f"{s['pass']} of {s['registered']} registered cases passed "
        f"({s['fail']} fail, {s['skipped']} skipped, {s['crashed']} crashed, "
        f"{s['error']} error) over {fmt(s['total_trials'])} trials."
    )
    if s["skipped"] or s["fail"] or s["crashed"] or s["error"]:
        out.append("")
        out.append(
            "> **This record is not clean.** A skipped case produced no evidence and must "
            "not be cited as if it had."
        )
    out.append("")
    out.append("| case | VA | model | status | trials | mismatches |")
    out.append("|---|---|---|---|---:|---:|")
    for c in d["cases"]:
        out.append(
            f"| `{c['id']}` | `{c['va']}` | `{c['model']}` | "
            f"**{c['status']}** | {fmt(c['trials'])} | {fmt(c['mismatches'])} |"
        )
    out.append("")

    for c in d["cases"]:
        out.append(f"### `{c['id']}` — {c['ledger_entry']}")
        out.append("")
        out.append("| field | value |")
        out.append("|---|---|")
        out.append(f"| source | `riseofnations.exe` VA `{c['va']}` ({c['abi']}) |")
        out.append(f"| implementation | `{c['model']}` |")
        out.append(f"| tier | **{c['tier']}** |")
        if c["status"] == "pass":
            out.append(f"| evidence | {evidence_sentence(c)} |")
        else:
            out.append(
                f"| evidence | **NONE — case status `{c['status']}`.** "
                f"{c.get('detail') or ''} |"
            )
        out.append(
            "| harness | `crates/oracle` `regress` command, "
            f"{d['target']} on `{d['host']}` |"
        )
        out.append(f"| reachability | {c['reachability']} |")
        out.append(f"| caveat | {c['caveat']} |")
        for k, v in c.get("extras", {}).items():
            if k == "step_coverage":
                continue
            out.append(f"| {k} | {v} |")
        out.append("")

    out.append("### Tier-B claims this suite does not re-run")
    out.append("")
    out.append(
        "Listed so a green suite is never mistaken for coverage of the whole ledger."
    )
    out.append("")
    out.append("| claim | why it is outside the harness |")
    out.append("|---|---|")
    for g in d["known_gaps"]:
        out.append(f"| {g['claim']} | {g['why']} |")
    out.append("")
    out.append(
        "Tier B is differential testing, not verification. Each count is a sample size "
        "over the stated distribution and says nothing about inputs outside it."
    )
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path", nargs="?", default=DEFAULT)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the record is missing, stale, or not all-pass",
    )
    ap.add_argument("--stale-days", type=int, default=STALE_DAYS)
    a = ap.parse_args()
    d = load(a.path)

    if a.check:
        rc = 0
        age = (time.time() - d["generated_unix"]) / 86400
        if d.get("exit_code") != 0:
            print(f"measurements are not clean: exit_code {d.get('exit_code')}")
            rc = 1
        if d["summary"]["skipped"]:
            print(f"{d['summary']['skipped']} cases SKIPPED — they produced no evidence")
            rc = 1
        if age > a.stale_days:
            print(f"measurements are {age:.0f} days old (> {a.stale_days})")
            rc = 1
        if d.get("only"):
            print(f"record is from a filtered run (--only {d['only']}); not full coverage")
            rc = 1
        if rc == 0:
            print(
                f"measurements clean: {d['summary']['pass']}/{d['summary']['registered']} "
                f"cases, {d['summary']['total_trials']:,} trials, {age:.1f} days old"
            )
        sys.exit(rc)

    print(render(d))


if __name__ == "__main__":
    main()
